Docs: Imporve documentation for the public api
hedgedoc/hedgedoc pull request #1047
Opened 2021-03-19 11:12 UTC by DerMolly

### Component/Part
apidocs

### Description
This PR improves documentation for the public api

### Steps

- [x] Added / updated documentation
- [x] I read the [contribution documentation](https://github.com/hedgedoc/hedgedoc/blob/develop/CONTRIBUTING.md) and
  made sure that:
  - My commits are signed-off to accept the DCO.
  - This PR targets the correct branch: `master` for 1.x & docs, `develop` for 2.x

2021-03-19 11:18 UTC, DerMolly commented
As far as I can tell from running https://github.com/OpenAPITools/openapi-diff with the generated api spec (`http://localhost:3000/apidoc-json`) and the handcrafted one the differences are still:
- `GET /api/v2/notes/{note}/media` is missing
- the Dtos changed on multiple occasions.
- `POST /api/v2/media` does not communicate the different types of images that are supported.

2021-03-19 21:44 UTC, InnayTool requested changes
Should the descriptions of the routes have a `.` at the end or not
(like
```
@ApiHeader({
    name: 'HedgeDoc-Note',
    description: 'ID or alias of the parent note',
})
```
or
```
@ApiHeader({
    name: 'HedgeDoc-Note',
    description: 'ID or alias of the parent note.',
})
```
)?
This seems to be inconsistent.

2021-03-19 21:44 UTC, InnayTool commented on src/api/public/me/me.controller.ts
> +    description: 'The history entry of the user and note',
```suggestion
    description: 'The history entry of the user which points to the note',
```

2021-03-19 21:44 UTC, InnayTool commented on src/api/public/notes/notes.controller.ts
> +    description: 'Revision of the note for the given id.',
```suggestion
    description: 'Revision of the note for the given id or alias.',
```

2021-03-20 08:44 UTC, DerMolly commented
> Should the descriptions of the routes have a `.` at the end or not
> 
> This seems to be inconsistent in the PR.

Well it's inconsistent in the base docs. I'd myself go with no periods.

2021-03-20 17:20 UTC, InnayTool approved these changes

2021-03-21 18:07 UTC, davidmehren approved these changes

2021-03-21 18:07 UTC, merged