API: Add option to keep media to DELETE /notes/{note}
hedgedoc/hedgedoc pull request #1094
Opened 2021-03-31 23:26 UTC by DerMolly

### Component/Part
public api, private api

### Description
This PR adds a body to the route DELETE /notes/{note} of the public and private api to specify if the associated media uploads of the note should be kept or deleted.

### Steps

- [x] Added implementation
- [x] Added / updated tests
- [x] I read the [contribution documentation](https://github.com/hedgedoc/hedgedoc/blob/develop/CONTRIBUTING.md) and
  made sure that:
  - My commits are signed-off to accept the DCO.
  - This PR targets the correct branch: `master` for 1.x & docs, `develop` for 2.x

### Related Issue(s)
fixes #1065

2021-04-01 00:01 UTC, DerMolly commented
If you check `yarn lint` the following error will be reported:

```
347:14  error  Avoid referencing unbound methods which may cause unintentional scoping of `this`.
If your function does not access `this`, you can annotate it with `this: void`, or consider using an arrow function instead  @typescript-eslint/unbound-method
```

the relevant code can be seen here:

https://github.com/hedgedoc/hedgedoc/blob/f4536460f5631d50fa684533fdc9a442084a2684/src/media/media.service.spec.ts#L340-L348

The documentation suggest disabling `@typescript-eslint/unbound-method` and using `jest/unbound-method` instead, but only for the tests. This would need a bigger change to the eslint config.

While Googling I found that the same error was already fixed in tslint (see [here](https://github.com/palantir/tslint/issues/4500) and [here](https://github.com/palantir/tslint/pull/4472)). As tslint is currently in the process of being incorporated into `@typescript-eslint` we could also try to raise an issue to get this fixed. But according to the [roadmap](https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/ROADMAP.md#L91) `@typescript-eslint/unbound-method` incorporates all of `tslint/no-unbound-method`, but it does not contain the whitelist. I guess this is because `jest/unbound-method` exists.

All this raises two questions:

1. Do we want to split the eslint config for tests and regular code? It seem we need to do that to get this probably fixed (we could of course also `eslint-disable` this one line of code).
2. Should either solution be part of this PR?
 
See: 
[`@typescript-eslint/unbound-method` docs](https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/docs/rules/unbound-method.md)
[`jest/unbound-method` docs](https://github.com/jest-community/eslint-plugin-jest/blob/main/docs/rules/unbound-method.md)

2021-04-02 18:18 UTC, InnayTool requested changes

2021-04-12 12:47 UTC, DerMolly commented on src/media/media.service.ts
> +  async deleteFileByFilename(
done

2021-04-13 19:36 UTC, InnayTool submitted a review, later dismissed

2021-04-18 20:25 UTC, InnayTool approved these changes

2021-04-18 20:49 UTC, InnayTool approved these changes

2021-04-22 18:49 UTC, InnayTool submitted a review, later dismissed

2021-04-22 21:09 UTC, davidmehren submitted a review, later dismissed

2021-04-22 21:14 UTC, davidmehren approved these changes

2021-04-22 21:15 UTC, InnayTool approved these changes

2021-04-22 21:18 UTC, merged