Add API decorator to reduce clutter
hedgedoc/hedgedoc pull request #1180
Opened 2021-04-25 00:33 UTC by glmdgrielson

### Component/Part
Backend

### Description
This PR adds a `FullApi` decorator for convenience's sake.

### Steps

- [x] Added implementation
- [x] I read the [contribution documentation](https://github.com/hedgedoc/hedgedoc/blob/develop/CONTRIBUTING.md) and
  made sure that:
  - My commits are signed-off to accept the DCO.
  - This PR targets the correct branch: `master` for 1.x & docs, `develop` for 2.x

### Related Issue(s)
Fixes #1063.

2021-04-25 09:18 UTC, DerMolly requested changes
Thanks for your work @glmdgrielson!
But your implementation doesn't seem to work. I think the way you wanted to combine the decorators is flawed.
![image](https://user-images.githubusercontent.com/3978662/115987969-c9e8af80-a5b7-11eb-8e18-b9ca0b5e28d2.png)

2021-04-25 09:18 UTC, DerMolly commented on src/api/utils/descriptions.ts
> +export const FullApi: MethodDecorator & ClassDecorator = function FullApi(target: any) {
Please define a function you want to export:

```suggestion
export function FullApi(target: any): : MethodDecorator & ClassDecorator {
```

2021-04-25 09:18 UTC, DerMolly commented on src/api/utils/descriptions.ts
> +export const FullApi: MethodDecorator & ClassDecorator = function FullApi(target: any) {
Please don't type anything as `any`. This is a bad practice. I'd suggest removing the target parameter and implementing this function with `applyDecorators` (see https://docs.nestjs.com/custom-decorators#decorator-composition)

2021-04-25 09:18 UTC, DerMolly commented on src/api/utils/descriptions.ts
> +export const FullApi: MethodDecorator & ClassDecorator = function FullApi(target: any) {
Our eslint config does not PascalCase, but this is of course the correct way of naming decorators.
You should add an extra line that tells eslint to ignore this one rule on this one line like we did with the MarkdownBody decorator:
https://github.com/hedgedoc/hedgedoc/blob/0c2900d1c033443c5d5d4f70dd4ebc1a3db72b51/src/api/utils/markdownbody-decorator.ts#L20-L24

2021-04-25 09:20 UTC, DerMolly commented
If your finished and before you commit I'd suggest you running `yarn lint:fix` and `yarn format:fix` to test if the linter and formater are happy (the `:fix` directly applies fixable suggestions to your code).

2021-04-25 17:43 UTC, glmdgrielson commented
Right, I've changed things to use `applyDecorators`. This is what I get for not reading the documentation.

2021-04-25 18:17 UTC, DerMolly approved these changes

2021-04-25 18:50 UTC, davidmehren approved these changes
Thanks, @glmdgrielson!

I'm happy to merge this as a single commit. If you are familiar with `git rebase -i`, please squash your commits. If not, no problem, I'd also be happy to squash for you.

2021-05-16 20:15 UTC, InnayTool approved these changes

2021-05-16 20:17 UTC, merged