Port over the FAQ page from hedgedoc.org to docs.hedgedoc.org
hedgedoc/hedgedoc pull request #1532
Opened 2021-08-12 21:01 UTC by davidmehren

### Component/Part
Docs

### Description
As more and more technical questions needed to be added to the FAQ, the hedgedoc.org homepage felt like the wrong place for it. This PR moves the technical questions into the documentation and adds some more Q&As. Having the FAQ on the docs page has the added benefit of the FAQ being included in the search.

### Steps

- [x] Added / updated documentation
- [x] I read the [contribution documentation](https://github.com/hedgedoc/hedgedoc/blob/develop/CONTRIBUTING.md) and
  made sure that:
  - My commits are signed-off to accept the DCO.
  - This PR targets the correct branch: `master` for 1.x & docs, `develop` for 2.x

### Related Issue(s)

2021-08-12 21:16 UTC, davidmehren commented
Deployed at https://hedgedoc-docs-staging--faq-isao5oy0.web.app/

2021-08-12 21:21 UTC, InnayTool approved these changes

2021-08-12 22:56 UTC, ErikMichelson requested changes

2021-08-12 22:56 UTC, ErikMichelson commented on docs/content/faq.md
> +## Why can I not embed a HedgeDoc note in other pages using iframes?
```suggestion
## Why can't I embed a HedgeDoc note in other pages using iframes?
```

Making it consistent with the previous question

2021-08-12 22:58 UTC, ErikMichelson requested changes
The index page contains a link to the old FAQ page which should be changed.

2021-08-13 20:44 UTC, DerMolly commented on docs/content/faq.md
> +- `cookiePolicy` / `CMD_COOKIE_POLICY` is set to `none` (Otherwise you will get a `AUTH failed: No cookie transmitted` error.)
Maybe we should link the corresponding part of the config docs here?

2021-08-14 09:06 UTC, davidmehren commented
I addressed the comments above and redeployed the current state to Firebase.

2021-08-14 09:15 UTC, DerMolly approved these changes

2021-08-14 22:09 UTC, ErikMichelson commented
Is there some way to set the page title for the search result? It takes the first heading from the file which is incorrect.

![image](https://user-images.githubusercontent.com/52606896/129461289-d720cd77-5731-469a-ae9c-92247030961b.png)

2021-08-19 18:22 UTC, davidmehren commented
@ErikMichelson fixed!

![image](https://user-images.githubusercontent.com/5023650/130123582-28fbf7bc-1b17-4d30-b787-0dbbacc39adc.png)

2021-08-19 19:30 UTC, ErikMichelson approved these changes

2021-08-19 19:31 UTC, merged