feat(config): Improve configurability of database by env
hedgedoc/hedgedoc pull request #1533
Opened 2021-08-12 23:42 UTC by SISheogorath

### Component/Part
configuration

### Description
This patch implements 6 additional environment variables that are used
for configuration of the database in order to allow easier configuration
in containerised environments, such as Kubernetes.

An example is the upcoming deployment of the demo instance that will use
an operator-backed postgresql database. This operator exposes username
and password as separate variables and while it's obviously possible to
generate a dbURL from that, this won't be possible without additional
code. Aiming for a solution in Hedgedoc itself, will help us to enable
other people in using Hedgedoc on Kubernetes without resulting in overly
customised setups for simple tasks like this.

### Steps

- [x] Added implementation
- [x] Added / updated tests -> not needed?
- [x] Added / updated documentation
- [x] I read the [contribution documentation](https://github.com/hedgedoc/hedgedoc/blob/develop/CONTRIBUTING.md) and
  made sure that:
  - My commits are signed-off to accept the DCO.
  - This PR targets the correct branch: `master` for 1.x & docs, `develop` for 2.x

### Related Issue(s)
none

2021-08-12 23:45 UTC, ErikMichelson requested changes

2021-08-12 23:45 UTC, ErikMichelson commented on lib/config/environment.js
> +  }
```suggestion
  },
```

2021-08-12 23:59 UTC, SISheogorath commented on lib/config/environment.js
> +  }
Thanks! 😅

2021-08-14 09:31 UTC, davidmehren approved these changes

2021-08-14 09:43 UTC, DerMolly approved these changes

2021-08-14 21:37 UTC, ErikMichelson approved these changes

2021-08-14 21:41 UTC, merged