Introduce RequestUser decorator
hedgedoc/hedgedoc pull request #1588
Opened 2021-08-28 17:04 UTC by davidmehren

### Component/Part
public API

### Description
This introduces the `RequestUser` decorator
to extract the `User` from a request.

It reduces code duplication across the public API
and allows us to drop the override of the `Request` type from express.

Signed-off-by: David Mehren <git@herrmehren.de>

### Steps

- [x] Added implementation
- [x] I read the [contribution documentation](https://github.com/hedgedoc/hedgedoc/blob/develop/CONTRIBUTING.md) and
  made sure that:
  - My commits are signed-off to accept the DCO.
  - This PR targets the correct branch: `master` for 1.x & docs, `develop` for 2.x

### Related Issue(s)

2021-08-28 20:11 UTC, InnayTool requested changes

2021-08-28 20:11 UTC, InnayTool commented on src/api/public/me/me.controller.ts
> +      await this.usersService.getUserByUsername(user.userName),
```suggestion
      user,
```

2021-08-28 20:16 UTC, InnayTool commented
I think adding this decorator is pretty nice. Should we do that for `Note` too?

2021-08-29 16:04 UTC, InnayTool approved these changes

2021-08-29 16:21 UTC, InnayTool approved these changes

2021-08-31 09:03 UTC, DerMolly commented
Should we put the handling of a username in a session in this decorator, too? Or should that be handled in a seperate decoractor? I'm tending towards the second option…

2021-08-31 09:08 UTC, DerMolly commented on src/auth/request-user.decorator.ts
> +/*
Also, should this file not be in `src/api/utils` like the other decorators?

2021-09-04 16:10 UTC, DerMolly approved these changes

2021-09-04 16:40 UTC, merged