Introduce GetNotePipe
hedgedoc/hedgedoc pull request #1589
Opened 2021-08-29 15:53 UTC by davidmehren

### Component/Part
Public & private API

### Description
This pipe transforms a note ID or alias to a Note object by loading it from the database.
It also performs error associated error handling.

### Steps

- [x] Added implementation
- [x] Added / updated tests
- [x] I read the [contribution documentation](https://github.com/hedgedoc/hedgedoc/blob/develop/CONTRIBUTING.md) and
  made sure that:
  - My commits are signed-off to accept the DCO.
  - This PR targets the correct branch: `master` for 1.x & docs, `develop` for 2.x

2021-08-29 15:53 UTC, davidmehren commented
Blocked by https://github.com/hedgedoc/hedgedoc/pull/1588

2021-08-29 20:57 UTC, InnayTool requested changes

2021-08-29 20:57 UTC, InnayTool commented on test/private-api/me.e2e-spec.ts
> +      note2,
This should be in one line.

2021-09-04 20:24 UTC, DerMolly commented on test/public-api/notes.e2e-spec.ts
> +        .expect(400);
404 isn't 400

2021-09-04 20:40 UTC, DerMolly approved these changes

2021-09-06 07:19 UTC, InnayTool approved these changes

2021-09-06 10:12 UTC, merged