feat: initialise special groups on bootstrap
hedgedoc/hedgedoc pull request #1794
Opened 2021-10-30 22:08 UTC by DerMolly

### Component/Part
groups / bootstrap 

### Description
This PR initialises special groups on bootstrap

### Steps

- [x] Added implementation
- [x] Added / updated tests
- [x] I read the [contribution documentation](https://github.com/hedgedoc/hedgedoc/blob/develop/CONTRIBUTING.md) and
  made sure that:
  - My commits are signed-off to accept the DCO.
  - This PR targets the correct branch: `master` for 1.x & docs, `develop` for 2.x

2021-10-30 22:23 UTC, InnayTool requested changes

2021-10-30 22:23 UTC, InnayTool commented on src/permissions/permissions.service.ts
>              // TODO: Name of group for logged in users
I think this can be removed now.

2021-10-30 22:25 UTC, DerMolly commented on src/permissions/permissions.service.ts
>              // TODO: Name of group for logged in users
Yeah, I guess so. Did that

2021-10-30 22:25 UTC, InnayTool approved these changes

2021-11-02 07:33 UTC, ErikMichelson requested changes

2021-11-02 07:33 UTC, ErikMichelson commented on src/groups/groups.service.spec.ts
> +    it('fails if username is already taken', async () => {
```suggestion
    it('fails if group name is already taken', async () => {
```

2021-11-02 07:33 UTC, ErikMichelson commented on src/groups/groups.service.spec.ts
> +      // create first user with username
```suggestion
      // create first group with group name
```

2021-11-02 07:33 UTC, ErikMichelson commented on src/groups/groups.service.spec.ts
> +      // attempt to create second user with username
```suggestion
      // attempt to create second group with group name
```

2021-11-02 07:33 UTC, ErikMichelson commented on src/groups/groups.service.ts
> +   * @param name - the username the new user shall have
```suggestion
   * @param name - the group name the new group shall have
```

2021-11-02 07:33 UTC, ErikMichelson commented on src/groups/groups.service.ts
> +   * @param displayName - the display the new user shall have
```suggestion
   * @param displayName - the display the new group shall have
```

2021-11-02 07:33 UTC, ErikMichelson commented on src/groups/groups.service.ts
> +        `A group with the username '${name}' already exists.`,
```suggestion
        `A group with the name '${name}' already exists.`,
```

2021-11-02 07:33 UTC, ErikMichelson commented on src/groups/groups.service.ts
> +        `A group with the username '${name}' already exists.`,
```suggestion
        `A group with the name '${name}' already exists.`,
```

2021-11-04 19:05 UTC, davidmehren requested changes

2021-11-04 19:05 UTC, davidmehren commented on src/groups/groups.service.spec.ts
> +        throw new Error();
This looks a bit suspicious. With this mock, `groupRepo.save` never succeeds, which should mean that `groupService.createGroup` also never succeeds.

2021-11-07 11:50 UTC, davidmehren approved these changes

2021-11-08 20:11 UTC, merged