Add Docs for getting started with 2.0
hedgedoc/hedgedoc pull request #1795
Opened 2021-10-30 23:04 UTC by Chasethechicken

### Component/Part
documentation

### Description
This PR adds documentation for how to set up HedgeDoc 2.0 for local development.

### Steps

- [x] Added  documentation
- [x] I read the [contribution documentation](https://github.com/hedgedoc/hedgedoc/blob/develop/CONTRIBUTING.md) and
  made sure that:
- [x] My commits are signed-off to accept the DCO.
- [x] This PR targets the correct branch: `master` for 1.x & docs, `develop` for 2.x

2021-12-07 16:11 UTC, InnayTool commented
How should we go on here?

2021-12-14 10:59 UTC, Chasethechicken commented
Sorry for taking so long. :sweat_smile: 
I have removed the incomplete section about starting Hedgedoc without auto-reload, as that is not really helpful for development and should be documented elsewhere.
I have also removed the *Dev Setup* section from *dev/2.0.md*, as it was essentially a shorter, less complete version of *dev/getting-started.md*.

2021-12-14 19:00 UTC, davidmehren requested changes

2021-12-14 19:00 UTC, davidmehren commented on docs/content/dev/getting-started.md
> +2. To auto-reload the server, enter the `hedgedoc` directory and run `yarn start:dev`.
```suggestion
2. To the server in auto-reload mode, enter the `hedgedoc` directory and run `env NODE_ENV=development yarn start:dev`.
```

2021-12-14 19:24 UTC, DerMolly commented on docs/content/dev/getting-started.md
> +2. To auto-reload the server, enter the `hedgedoc` directory and run `yarn start:dev`.
I think your missing a `start` there?

2021-12-15 16:04 UTC, ErikMichelson commented on docs/content/dev/getting-started.md
> +   **Note:** You can run `yarn start:for-real-backend` to start a frontend, which tries to connect to a local backend.
Typo in your suggestion: "to start a frontend with an integrated" instead of "to start a frontend with in integrated".

2021-12-18 15:55 UTC, DerMolly approved these changes
LGTM

2021-12-18 21:35 UTC, ErikMichelson commented
Thanks! Please ensure to accept the [DCO](https://github.com/hedgedoc/hedgedoc/blob/develop/docs/content/legal/developer-certificate-of-origin.txt) and [contribution guidelines](https://github.com/hedgedoc/hedgedoc/blob/develop/CONTRIBUTING.md) by signing-off your commits.

2021-12-20 12:25 UTC, Chasethechicken commented
Sorry, all my commits are now signed-off.

2021-12-21 09:52 UTC, Chasethechicken commented
I have updated the testing paragraph, do you think it is correct now?
I guess it is kind of confusing, that `yarn start:for-real-backend` automatically opens `http://localhost:3001` in your browser, which is not what you want to be looking at. :sweat_smile:

2021-12-21 10:30 UTC, ErikMichelson commented
Well that's a good point. We should probably disable that.
Thanks for your changes, from my persepctive they seem good in that way.

2021-12-21 10:40 UTC, ErikMichelson approved these changes

2021-12-21 16:24 UTC, davidmehren approved these changes

2021-12-21 16:24 UTC, merged