fix(auth): use sha-512 for auth tokens
hedgedoc/hedgedoc pull request #1882
Opened 2021-12-09 22:05 UTC by davidmehren

### Component/Part
Auth Tokens

### Description
Bcrypt hashes are too slow to be validated on every request.
As our tokens are random and have a fixed length, it is reasonable
to use SHA-512 instead.

SHA-512 is recommended by the BSI:
https://www.bsi.bund.de/SharedDocs/Downloads/EN/BSI/Publications/TechGuidelines/TG02102/BSI-TR-02102-1.pdf?__blob=publicationFile

Fixes https://github.com/hedgedoc/hedgedoc/issues/1881

### Steps

- [x] Added implementation
- [x] Added / updated tests
- [x] I read the [contribution documentation](https://github.com/hedgedoc/hedgedoc/blob/develop/CONTRIBUTING.md) and
  made sure that:
  - My commits are signed-off to accept the DCO.
  - This PR targets the correct branch: `master` for 1.x & docs, `develop` for 2.x

### Related Issue(s)

2021-12-09 22:34 UTC, DerMolly commented on src/auth/auth.service.ts
> +    const secret = bufferToBase64Url(randomBytes(64));
This change is currently a bit unexplained. I'd suggest changing that.

2021-12-09 22:34 UTC, DerMolly approved these changes
LGTM

2021-12-10 03:02 UTC, SISheogorath commented
> SHA-512 is recommended by the BSI:
https://www.bsi.bund.de/SharedDocs/Downloads/EN/BSI/Publications/TechGuidelines/TG02102/BSI-TR-02102-1.pdf?__blob=publicationFile

Uhm, which section are you refering to? I don't think they talk about our use-case anywhere in that document. Section 6.1 recommends to do challenge-response for authentication with a shared secret. Otherwise it's quite silent on this part.

2021-12-12 10:31 UTC, InnayTool requested changes

2021-12-12 10:31 UTC, InnayTool commented on src/auth/auth.service.ts
> +    const accessToken = crypto
I think that it should be named `accessTokenHash` to make clearer it is not the actual token.

2021-12-13 21:45 UTC, davidmehren commented
I updated the PR according to the reviews and expanded some comments

2021-12-13 21:56 UTC, davidmehren commented
Regarding the use of SHA-512:
Unfortunately, I could not find any explicit documentation about our exact use-case.
Most docs describe classic password-saving scenarios and recommend bcrypt, scrypt or argon2. These hashing functions are slow to stop brute-force or dictionary attacks, which would expose the original, user-provided password, which might have been reused across multiple services.

We have a very different scenario: Our API tokens are 64 bytes of cryptographically strong pseudorandom data. Brute-force or dictionary attacks are therefore virtually impossible, and they are not reused across multiple services. We therefore need to only guard against one scenario: An attacker gains read-only access to the database. Saving only hashes in the database prevents the attacker from authenticating themselves as a user. The hash-function does not need to be very slow, as the randomness of the original token prevents inverting the hash. The function actually needs to be reasonably fast, as the hash must be computed on every request to the public API. SHA-512 (or alternatively SHA3) fits this use-case.

2021-12-14 12:26 UTC, SISheogorath commented
@davidmehren 👍🏻 This sounds better :)

2021-12-14 18:21 UTC, davidmehren commented
@SISheogorath Great idea, I added the explanation to the docs.

2021-12-14 18:31 UTC, InnayTool requested changes

2021-12-14 18:31 UTC, InnayTool commented on docs/content/dev/2.0.md
> +The public uses bearer tokens for authentication.
```suggestion
The public API uses bearer tokens for authentication.
```

2021-12-14 18:38 UTC, InnayTool approved these changes

2021-12-14 18:41 UTC, merged