Documentation & working example for Authelia OAuth SSO
hedgedoc/hedgedoc pull request #1953
Opened 2022-01-05 16:13 UTC by DennisGaida

### Component/Part
Documentation

### Description
This PR adds documentation and a working example for setting up OAuth SSO with Authelia ([www.authelia.com](https://github.com/authelia/authelia))

### Steps

- [ ] Added implementation
- [ ] Added / updated tests
- [x] Added documentation
- [ ] Added changelog snippet
- [x] I read the [contribution documentation](https://github.com/hedgedoc/hedgedoc/blob/develop/CONTRIBUTING.md) and
  made sure that:
  - My commits are signed-off to accept the DCO.
  - This PR targets the correct branch: `master` for 1.x & docs, `develop` for 2.x

2022-01-06 07:59 UTC, DerMolly requested changes
Hey @DennisGaida,

thank you for this contribution. I added some suggestion what could be improved with the guide.

Somebody will also need to verify this works by trying out this guide, as I did not do that yet.

Also please make sure that you [Sign-Off your commits](https://docs.pi-hole.net/guides/github/how-to-signoff/). Note that signing off your commits accepts our DCO, a legally binding statement. Please carefully read our [contribution docs](https://github.com/hedgedoc/hedgedoc/blob/develop/CONTRIBUTING.md#certificate-of-origin).

2022-01-06 07:59 UTC, DerMolly commented on docs/content/guides/auth/authelia.md
> +This guide assumes you have run and configured [Authelia](https://www.authelia.com/). If you want to get Authelia running quickly, there are example docker-compose files in the Authelia Github reposi
```suggestion
This guide assumes you have run and configured [Authelia](https://www.authelia.com/). If you want to get Authelia running quickly, there are example docker-compose files in the [Authelia Github repository](https://github.com/authelia/authelia/tree/master/examples/compose).
```

2022-01-06 07:59 UTC, DerMolly commented on docs/content/guides/auth/authelia.md
> +
```suggestion
Also this guides assumes you run HedgeDoc via a [Docker container](../../setup/docker.md). Find out how the mentioned config environment variables are mapped to entries in the config file at our [configuration page](../../configuration.md).

```

2022-01-06 07:59 UTC, DerMolly commented on docs/content/guides/auth/authelia.md
> +      - id: HedgeDoc
```suggestion
      - id: HedgeDoc # this should be changed to something more secure
```

2022-01-06 08:29 UTC, DennisGaida commented
Hmhmm I guess I should have first accept the changes, then `signoff` the previous commits and force push?

2022-01-06 08:37 UTC, DennisGaida commented
Great, now I can't sign off on these three review/change commits I just clicked in the GH UI since it doesn't automatically sign off. Of course I can't force push to this repo. How do we proceed - I don't think I can sign-off on these changes?

2022-01-06 10:39 UTC, mrdrogdrog commented
You can force push into your own fork.

2022-01-16 18:22 UTC, davidmehren approved these changes

2022-01-29 16:16 UTC, DerMolly approved these changes

2022-01-29 16:16 UTC, merged