Do not embed User/Group objects
hedgedoc/hedgedoc pull request #1987
Opened 2022-01-16 21:56 UTC by davidmehren

### Component/Part
API

### Description
This PR removes embedded user and group objects from the API

### Steps

- [x] Added implementation
- [x] Added / updated tests
- [x] I read the [contribution documentation](https://github.com/hedgedoc/hedgedoc/blob/develop/CONTRIBUTING.md) and
  made sure that:
  - My commits are signed-off to accept the DCO.
  - This PR targets the correct branch: `master` for 1.x & docs, `develop` for 2.x

2022-01-16 22:13 UTC, ErikMichelson requested changes

2022-01-16 22:13 UTC, ErikMichelson commented on src/notes/note-permissions.dto.ts
Unused imports above

2022-01-20 20:40 UTC, InnayTool approved these changes

2022-01-21 11:10 UTC, DerMolly approved these changes

2022-01-23 01:55 UTC, ErikMichelson approved these changes

2022-01-23 09:45 UTC, merged