Add APIs to fetch info about Users and Groups
hedgedoc/hedgedoc pull request #2145
Opened 2022-02-27 18:08 UTC by davidmehren

### Component/Part
Private API

### Description
This PR adds routes that allow to fetch information about users and groups given their respective names.

### Steps

- [x] Added implementation
- [x] Added / updated tests
- [x] I read the [contribution documentation](https://github.com/hedgedoc/hedgedoc/blob/develop/CONTRIBUTING.md) and
  made sure that:
  - My commits are signed-off to accept the DCO.
  - This PR targets the correct branch: `master` for 1.x & docs, `develop` for 2.x

2022-02-27 19:21 UTC, ErikMichelson commented on src/api/private/private-api.module.ts
> +    UserController,
Duplicate

2022-02-27 19:54 UTC, ErikMichelson requested changes

2022-02-27 19:54 UTC, ErikMichelson commented on src/api/private/group/group.controller.ts
> + */
Copyright written twice

2022-02-27 20:24 UTC, ErikMichelson approved these changes

2022-02-28 11:40 UTC, InnayTool approved these changes

2022-03-01 19:20 UTC, merged