Add a Dockerfile
hedgedoc/hedgedoc pull request #2149
Opened 2022-03-03 20:45 UTC by davidmehren

### Component/Part
Docker

### Description
This PR adds a `Dockerfile` and necessary changes to our Yarn infrastructure to install prod-only dependencies.
It also includes a refactor that ensures the app works with prod-only dependencies.

I added the documentation for using the Dockerfile directly in the `docker` directory, instead of the docs, as I found it more immediately helpful there. Especially as docs.hedgedoc.org is deployed from `master`.

I plan to add more infrastructure to the `docker` folder in the future, including a `docker-compose.yml` to help testing with different databases.

### Steps

- [x] Added implementation
- [x] Added / updated documentation
- [x] I read the [contribution documentation](https://github.com/hedgedoc/hedgedoc/blob/develop/CONTRIBUTING.md) and
  made sure that:
  - My commits are signed-off to accept the DCO.
  - This PR targets the correct branch: `master` for 1.x & docs, `develop` for 2.x

### Related Issue(s)

2022-03-03 23:26 UTC, DerMolly commented
One thought that just came up: Do we want to keep the `.spec`-Files in the container? I mean we need them in the development stage, but strictly speaking leaving them out for the production container would save a bit space.

2022-03-03 23:50 UTC, DerMolly commented on docker/README.md
> +`docker run -e HD_DOMAIN=localhost -e HD_MEDIA_BACKEND=filesystem -e HD_MEDIA_BACKEND_FILESYSTEM_UPLOAD_PATH=uploads -e HD_DATABASE_DIALECT=sqlite -e HD_DATABASE_STORAGE=hedgedoc.sqlite -e HD_SESSION
```suggestion
`docker run -e HD_DOMAIN=http://localhost -e HD_MEDIA_BACKEND=filesystem -e HD_MEDIA_BACKEND_FILESYSTEM_UPLOAD_PATH=uploads -e HD_DATABASE_DIALECT=sqlite -e HD_DATABASE_STORAGE=hedgedoc.sqlite -e HD_SESSION_SECRET=foobar -e HD_LOGLEVEL=debug -p 3000:3000 hedgedoc-prod`
```

2022-03-04 08:45 UTC, davidmehren commented on docker/README.md
> +`docker build -t hedgedoc-prod -f docker/Dockerfile .`
I will emphasize the note about the working directory. Unfortunately, due to the way docker works, there is no way around this.

2022-03-04 11:23 UTC, ErikMichelson commented on docker/Dockerfile
> +    YARN_CACHE_FOLDER=/tmp/.yarn yarn install --immutable && \
This install is superfluous as the `yarn workspaces focus` already does an install. See [the docs](https://yarnpkg.com/cli/workspaces/focus). So this install just adds all development dependencies as well (which is not what we want in the prod image).

2022-03-04 13:11 UTC, ErikMichelson commented
We could add the [OCI Annotations](https://github.com/opencontainers/image-spec/blob/main/annotations.md) to the resulting docker image.

2022-03-05 20:33 UTC, ErikMichelson requested changes
## Production image

This image does not work!
The copy of the `dist` folder directly into the root of `/usr/src/app` results in invalid path levels, leading to errors like this one:
```
[HedgeDoc.ExceptionsHandler()] ENOENT: no such file or directory, open '/usr/src/package.json'
```

Otherwise, the production image is good, especially the size is a decrese of 150 MB compared to the alpine docker image of HedgeDoc 1.x.

<details>
<summary>Stats</summary>

```
Total Image size: 234 MB
Potential wasted space: 730 kB
Image efficiency score: 99 %
```

</details>

## Development image

The development image works as expected.

<details>
<summary>Stats</summary>

```
Total Image size: 459 MB
Potential wasted space: 730 kB
Image efficiency score: 99 %
```

</details>

2022-03-06 19:58 UTC, DerMolly approved these changes

2022-03-06 21:32 UTC, InnayTool approved these changes

2022-03-07 12:50 UTC, ErikMichelson approved these changes

2022-03-07 12:55 UTC, merged