docs: consolidate community install methods
hedgedoc/hedgedoc pull request #2336
Opened 2022-05-08 21:17 UTC by DerMolly

### Component/Part
Docs

### Description
This PR adds all community install methods to a single page. This seems to be a better option as all of these methods have very little to document and this makes it easier to browse through the different methods.

### Steps

- [x] Added / updated documentation
- [x] I read the [contribution documentation](https://github.com/hedgedoc/hedgedoc/blob/develop/CONTRIBUTING.md) and
  made sure that:
  - My commits are signed-off to accept the DCO.
  - This PR targets the correct branch: `master` for 1.x & docs, `develop` for 2.x

2022-05-17 11:49 UTC, davidmehren requested changes

2022-05-17 11:49 UTC, davidmehren commented on docs/content/dev/getting-started.md
> +**Notice:** *There's [specialised instructions for docker](../setup/docker.md) if you prefer running code this way!*
```suggestion
**Notice:** *There are [specialised instructions for docker](../setup/docker.md) if you prefer running code this way!*
```

2022-05-17 11:49 UTC, davidmehren commented on docs/content/setup/community.md
> +# Community installation methods
```suggestion
# Community Installation Methods
```

2022-05-17 11:49 UTC, davidmehren commented on docs/content/setup/community.md
> +### LinuxServer.io Docker image
```suggestion
### LinuxServer.io Docker Image
```

2022-05-17 11:49 UTC, davidmehren commented on docs/content/setup/community.md
> +The HedgeDoc community has created and tested many options for deploying HedgeDoc on other platforms or operating systems.
```suggestion
The HedgeDoc community has created and tested many options for deploying HedgeDoc on other platforms or operating systems.
These are not officially supported by the HegeDoc maintainers. If you encounter issues or have questions, please first reach out to downstream packagers.
```

2022-05-17 11:49 UTC, davidmehren commented on docs/content/setup/community.md
> +[LinuxServer.io](https://linuxserver.io) have created an Ubuntu-based multi-arch container image for x86-64, arm64 and armhf.
```suggestion
[LinuxServer.io](https://linuxserver.io) have created an Alpine-based multi-arch container image for x86-64, arm64 and armhf.
```
https://github.com/linuxserver/docker-hedgedoc/blob/main/Dockerfile#L1

2022-05-17 11:49 UTC, davidmehren commented on docs/mkdocs.yml
> +      - 'Community installation methods': setup/community.md
```suggestion
      - 'Community Installation Methods': setup/community.md
```

2022-05-18 08:32 UTC, ErikMichelson commented on docs/content/setup/community.md
> +# Community installation methods
fixed

2022-05-18 08:32 UTC, ErikMichelson commented on docs/content/setup/community.md
> +### LinuxServer.io Docker image
fixed

2022-05-18 08:32 UTC, ErikMichelson commented on docs/mkdocs.yml
> +      - 'Community installation methods': setup/community.md
fixed

2022-05-18 08:33 UTC, davidmehren approved these changes

2022-05-18 08:41 UTC, merged