Upload file to s3: make public a file on upload and allow to configure destination folder
hedgedoc/hedgedoc pull request #2385
Opened 2022-05-25 20:24 UTC by lautaroalvarez

### Component/Part
s3 imageRouter (`lib/web/imageRouter/s3.js`)

### Description
New configurations:
- s3folder: (string) folder to save the files inside bucket
- s3publicFiles: (boolean) indicate if should send ACL parameters

When `s3publicFiles` is true we add the ACL parameter to the `s3.putObject` function.

Aws doc: https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/S3.html#putObject-property . The paremeter is `ACL`. The value we want is "public-read"

### Steps
- [x] Added implementation
- [x] Added / updated documentation
- [x] I read the [contribution documentation](https://github.com/hedgedoc/hedgedoc/blob/develop/CONTRIBUTING.md) and
  made sure that:
  - My commits are signed-off to accept the DCO.
  - This PR targets the correct branch: `master` for 1.x & docs, `develop` for 2.x

### Related Issue(s)
https://github.com/hedgedoc/hedgedoc/issues/2384

2022-06-05 18:53 UTC, davidmehren commented
We do not accept new features for HedgeDoc 1.x anymore, as stated in the [README](https://github.com/hedgedoc/hedgedoc#state-of-the-project):
> The 1.x release is maintenance-only. We do not accept feature requests or PRs for this release anymore and may choose to close non-critical bug reports, if the bug will be non-existent in 2.0.

2022-06-05 19:59 UTC, lautaroalvarez commented
@davidmehren but It's a bug: I can't use it with my digitalocean space as S3 because it uploads files without public permissions. The important change is the line https://github.com/hedgedoc/hedgedoc/pull/2385/files#diff-49ad4b49eb8a16cecc65109370e1545513dc4017586b811f04dfc4124a449f3eR37 . Maybe I have to remove the other changes because they can be interpreted as "new features".

I have added a new environment configuration "s3publicFiles" because I don't want to change the current use of s3.

Is there any way I can apply this fix? Because I really want to use Hedgedoc with my digitalocean space.

2022-06-12 18:19 UTC, davidmehren commented
We just discussed this again and decided to accept this as a bugfix.

2022-06-12 19:38 UTC, davidmehren commented on docs/content/configuration.md
> +| `s3folder`  | `CMD_S3_FOLDER`            | 'uploads'                                                                                                         | Folder where the files will be saved i
The `s3publicFiles` option should also be documented.

2022-06-26 18:56 UTC, davidmehren requested changes
Just one last thing regarding wording

2022-06-26 18:56 UTC, davidmehren commented on docs/content/configuration.md
> +| `s3publicFiles` | `CMD_S3_PUBLIC_FILES`      | `false`                                                                                                           | If se to `true` set public permiss
```suggestion
| `s3publicFiles` | `CMD_S3_PUBLIC_FILES`      | `false`                                                                                                           | If set to `true`, a `public-read` ACL is applied to uploaded objects                                                               |
```

2022-06-27 11:32 UTC, lautaroalvarez commented on docs/content/configuration.md
> +| `s3publicFiles` | `CMD_S3_PUBLIC_FILES`      | `false`                                                                                                           | If se to `true` set public permiss
Much better

2022-06-27 13:59 UTC, InnayTool approved these changes

2022-06-27 19:06 UTC, davidmehren approved these changes

2022-07-10 15:44 UTC, merged