Add more E2E tests
hedgedoc/hedgedoc pull request #2455
Opened 2022-06-19 20:19 UTC by davidmehren

### Description
This PR adds more end-to-end tests

### Steps

- [x] Added / updated tests
- [x] I read the [contribution documentation](https://github.com/hedgedoc/hedgedoc/blob/develop/CONTRIBUTING.md) and
  made sure that:
  - My commits are signed-off to accept the DCO.
  - This PR targets the correct branch: `master` for 1.x & docs, `develop` for 2.x

### Related Issue(s)

2023-02-12 20:46 UTC, mrdrogdrog approved these changes

2023-02-12 20:53 UTC, DerMolly approved these changes

2023-02-12 20:58 UTC, mrdrogdrog requested changes

2023-02-12 20:58 UTC, mrdrogdrog commented on backend/test/test-setup.ts
> +    process.env.HD_DOMAIN =
HD_DOMAIN doesn't exist anymore

2023-02-16 17:54 UTC, InnayTool approved these changes

2023-02-19 19:53 UTC, mrdrogdrog approved these changes

2023-02-19 19:56 UTC, merged