Convert history attribute in user table to longtext
hedgedoc/hedgedoc pull request #2624
Opened 2022-09-01 08:37 UTC by mrdrogdrog

### Component/Part
Database scheme

### Description
This PR changes the data type of the history attribute in the user table to long text.

When using mysql the normal text attribute has a fixed size. When this size is reached then the json will be cut off and becomes invalid. The problem doesn't occur when using postgres or sqlite because they already have variable length.

### Steps

- [x] Added implementation
- [ ] Added changelog snippet
- [x] I read the [contribution documentation](https://github.com/hedgedoc/hedgedoc/blob/develop/CONTRIBUTING.md) and
  made sure that:
  - My commits are signed-off to accept the DCO.
  - This PR targets the correct branch: `master` for 1.x & docs, `develop` for 2.x

### Related Issue(s)
Fixes #2623

2022-09-01 11:26 UTC, ErikMichelson approved these changes

2022-09-03 07:46 UTC, InnayTool approved these changes

2022-09-04 18:49 UTC, DerMolly approved these changes

2022-09-11 13:22 UTC, davidmehren requested changes

2022-09-11 13:22 UTC, davidmehren commented on lib/migrations/20220901102800-convert-history-to-longtext.js
> +  up: function (queryInterface, Sequelize) {
Please add a `down` method too.

2022-09-11 13:25 UTC, davidmehren commented on public/docs/release-notes.md
> +- Change data type of history attribute in user table to long text to prevent truncated json when using mysql
```suggestion
- Fix crash caused by a long note history when the MySQL database is used
```

2022-09-25 09:09 UTC, davidmehren approved these changes

2022-09-25 09:09 UTC, merged