Update `yaml-metadata.md`.
hedgedoc/hedgedoc pull request #2625
Opened 2022-09-01 09:15 UTC by drupol

Update `slideOptions` documentation and links.

### Component/Part

### Description
This PR fixes/adds/improves/...

### Steps

- [ ] Added implementation
- [ ] Added / updated tests
- [ ] Added / updated documentation
- [ ] Added changelog snippet
- [ ] I read the [contribution documentation](https://github.com/hedgedoc/hedgedoc/blob/develop/CONTRIBUTING.md) and
  made sure that:
  - My commits are signed-off to accept the DCO.
  - This PR targets the correct branch: `master` for 1.x & docs, `develop` for 2.x

### Related Issue(s)

2022-09-01 09:23 UTC, mrdrogdrog requested changes

2022-09-01 09:30 UTC, drupol commented on public/docs/yaml-metadata.md
> +In HedgeDoc 1, Reveal version 3 is in use.
Done.

2022-09-01 10:52 UTC, InnayTool requested changes

2022-09-01 10:52 UTC, InnayTool commented on public/docs/yaml-metadata.md
> +See the below document for more details on the available slide options:
```suggestion
See the document below for more details on the available slide options:
```

2022-09-02 18:19 UTC, ErikMichelson approved these changes

2022-09-03 07:47 UTC, InnayTool approved these changes

2022-09-03 07:48 UTC, mrdrogdrog approved these changes

2022-09-03 16:09 UTC, DerMolly approved these changes

2022-09-05 08:11 UTC, merged