feat: allow guests in HedgeDoc 2
hedgedoc/hedgedoc pull request #2716
Opened 2022-10-02 18:50 UTC by DerMolly

### Component/Part
guest access

### Description
This PR adds guest access to the application.

### Steps

- [ ] Added implementation
- [ ] Added / updated tests
- [ ] Added / updated documentation
- [ ] Added changelog snippet
- [ ] I read the [contribution documentation](https://github.com/hedgedoc/hedgedoc/blob/develop/CONTRIBUTING.md) and
  made sure that:
  - My commits are signed-off to accept the DCO.
  - This PR targets the correct branch: `master` for 1.x & docs, `develop` for 2.x

### Related Issue(s)

2022-10-09 19:08 UTC, InnayTool approved these changes

2022-10-16 19:21 UTC, mrdrogdrog approved these changes

2022-10-24 06:27 UTC, InnayTool approved these changes

2022-10-30 16:16 UTC, davidmehren requested changes

2022-10-30 16:16 UTC, davidmehren commented on src/api/utils/request-user.decorator.ts
>   *
```suggestion
/**
 * Trys to extract the {@link User} object from a request
 *
 * If a user is present in the request, returns the user object.
 * If no user is present and guests are allowed, returns `null`.
 * If no user is present and guests are not allowed, throws {@link UnauthorizedException}.
```

2022-10-30 16:16 UTC, davidmehren commented on src/identity/session.guard.ts
> +      if (this.noteConfig.guestAccess !== GuestAccess.DENY) {
I feel like this if-statement (and with it this class) is now complicated enough to warrant some docs/comments.

2022-10-30 16:35 UTC, davidmehren approved these changes

2022-10-30 19:50 UTC, merged