fix: Remove all `Equal` in where Clause in `find`
hedgedoc/hedgedoc pull request #2718
Opened 2022-10-02 19:34 UTC by InnayTool

### Component/Part
Services

### Description
Remove all `Equal` in where Clause in `find` to fix #2467.

### Steps

- [x] Added implementation
- [x] Added / updated tests
- [x] I read the [contribution documentation](https://github.com/hedgedoc/hedgedoc/blob/develop/CONTRIBUTING.md) and
  made sure that:
  - My commits are signed-off to accept the DCO.
  - This PR targets the correct branch: `master` for 1.x & docs, `develop` for 2.x

### Related Issue(s)
#2467

2022-10-02 20:06 UTC, davidmehren approved these changes

2022-10-03 08:40 UTC, DerMolly requested changes

2022-10-03 08:40 UTC, DerMolly commented on src/history/history.service.spec.ts
> +        }),
Should this still be here?

2022-10-22 10:19 UTC, davidmehren approved these changes

2022-10-30 17:15 UTC, merged