Add turbo monorepo utility
hedgedoc/hedgedoc pull request #3035
Opened 2022-12-12 00:24 UTC by ErikMichelson

### Component/Part
CI / monorepo

### Description
This PR adds [turbo](https://turbo.build/repo) as a mono-repo utility (after lerna didn't work properly).
It is currently used to build, lint and format the different parts of the project with one command from the repository root (`yarn build`, `yarn lint`, `yarn format`).
This PR changes the workflows to use one common job for linting and checking formatting of all project parts using the new turbo commands.

### Steps
- [x] I read the [contribution documentation](https://github.com/hedgedoc/hedgedoc/blob/develop/CONTRIBUTING.md) and
  made sure that:
  - My commits are signed-off to accept the DCO.
  - This PR targets the correct branch: `master` for 1.x & docs, `develop` for 2.x

### Related Issue(s)
none

2022-12-18 19:31 UTC, mrdrogdrog requested changes

2022-12-18 19:57 UTC, mrdrogdrog commented
To improve development and CI runs we could host this https://ducktors.github.io/turborepo-remote-cache/

2022-12-18 19:58 UTC, davidmehren commented
We can probably also add a `test` job to turbo and then get rid of our complicated CI job setup that detects changed files, as turbo should do that for us.

2022-12-18 22:04 UTC, ErikMichelson commented on backend/docker/Dockerfile
> +RUN apk add --no-cache tini libc6-compat
Without this package yarn install fails completely.

2022-12-25 13:30 UTC, mrdrogdrog commented on backend/docker/Dockerfile
> +RUN apk add --no-cache tini libc6-compat
Yes, but neither yarn nor turbo are used in the "prod" stage but by adding this package HERE you include the lib into the stages.

2023-01-09 11:50 UTC, davidmehren approved these changes

2023-01-09 11:56 UTC, mrdrogdrog commented
What about the token bar?

2023-01-09 12:59 UTC, mrdrogdrog commented
Btw: the official remote cache is hosted by vercel. It seems like they do this for free. So we don't need to host the cache ourself. 🤷

2023-01-09 13:49 UTC, mrdrogdrog commented
The test workflow hasn't been adjusted.

Remember to include the node version into the turbo dependencies

2023-01-09 19:12 UTC, mrdrogdrog commented
How do we handle flakiness? You can force the rerun of tests.. Should we consider this somehow?

2023-01-15 22:38 UTC, ErikMichelson commented
@davidmehren The required workflows need to be adjusted for allowing merges.

2023-02-06 19:57 UTC, mrdrogdrog approved these changes

2023-02-06 20:59 UTC, DerMolly approved these changes

2023-02-06 21:02 UTC, ErikMichelson reviewed
LGTM ✅

2023-02-07 18:58 UTC, davidmehren commented on .github/workflows/docker.yml
> +        uses: docker/build-push-action@c56af957549030174b10d6867f20e78cfd7debc5 # v3.2.0
This should probably use the same version as line 76?

2023-02-07 18:58 UTC, davidmehren commented on .github/workflows/docker.yml
> +        uses: docker/metadata-action@57396166ad8aefe6098280995947635806a0e6ea # v4.1.1
This should probably use the same version as line 38?

2023-02-07 19:34 UTC, ErikMichelson commented on docs/content/dev/getting-started.md
> +5. Goto `hedgedoc/backend` directory with `cd ../backend`
Why `../backend`? Following the guide step-by-step, we're still in the repo root directory.
Furthermore, we first download caddy to `hedgedoc/dev-reverse-proxy` and then create the `hedgedoc` folder afterwards by the `git clone`. This won't work.

2023-02-07 19:41 UTC, ErikMichelson commented on frontend/docker/Dockerfile
> +ENTRYPOINT ["tini"]
The [official documentation](https://github.com/krallin/tini#using-tini) sets the entrypoint slightly different.

```suggestion
ENTRYPOINT ["tini", "--"]
```

2023-02-07 19:52 UTC, ErikMichelson commented on package.json
> +    "format": "turbo run format",
This errors:
```
 ERROR  run failed: task `format` not found in turbo `pipeline` in "turbo.json". Are you sure you added it?
```

2023-02-07 20:22 UTC, ErikMichelson reviewed
Seems good now

2023-02-07 20:38 UTC, merged