Fix image uploads
hedgedoc/hedgedoc pull request #3094
Opened 2022-12-28 17:22 UTC by davidmehren

### Component/Part
The upload stack™

### Description
This PR fixes image uploads by
- improving error handling on empty uploads slightly
- not sending the `Content-Type` header, which confuses multer
- configuring Caddy to proxy the uploads route to the backend
### Steps

- [x] Added implementation
- [ ] Added changelog snippet
- [x] I read the [contribution documentation](https://github.com/hedgedoc/hedgedoc/blob/develop/CONTRIBUTING.md) and
  made sure that:
  - My commits are signed-off to accept the DCO.
  - This PR targets the correct branch: `master` for 1.x & docs, `develop` for 2.x

### Related Issue(s)

2022-12-28 17:27 UTC, InnayTool approved these changes

2022-12-28 18:20 UTC, mrdrogdrog requested changes

2022-12-28 18:20 UTC, mrdrogdrog commented on backend/src/api/private/media/media.controller.ts
> +    }
what about the missing test?

2022-12-30 09:22 UTC, davidmehren commented on backend/src/api/private/media/media.controller.ts
> +    }
Test added

2022-12-30 09:31 UTC, mrdrogdrog approved these changes

2022-12-30 10:02 UTC, merged