ci: Add OpenSSF scorecard setup
hedgedoc/hedgedoc pull request #3117
Opened 2023-01-06 10:38 UTC by SISheogorath

### Component/Part
Continuous Integration 

### Description
This patch enables a new GitHub action that runs on each commit and updates the HedgeDoc OpenSSF scorecard score, which is a combination of various project best practices that are actively worked on. This should help to stay on top of current best practices and provide transparency for users of HedgeDoc.

### Steps

- [x] Added / updated tests
- [x] I read the [contribution documentation](https://github.com/hedgedoc/hedgedoc/blob/develop/CONTRIBUTING.md) and
  made sure that:
  - My commits are signed-off to accept the DCO.
  - This PR targets the correct branch: `master` for 1.x & docs, `develop` for 2.x

2023-01-06 10:48 UTC, mrdrogdrog requested changes
You forgot to add the SPDX header

2023-01-06 11:19 UTC, SISheogorath commented
Fixed, thanks for the hint!

2023-01-06 12:37 UTC, mrdrogdrog approved these changes

2023-01-08 12:52 UTC, DerMolly approved these changes

2023-01-08 18:07 UTC, davidmehren commented
Shouldn't we also display the badge somewhere?

2023-01-08 20:59 UTC, ErikMichelson approved these changes

2023-01-08 21:01 UTC, InnayTool approved these changes

2023-01-08 21:08 UTC, merged