API documentation (Swagger): Version number + paths
hedgedoc/hedgedoc pull request #3146
Opened 2023-01-08 23:48 UTC by ErikMichelson

### Component/Part
API documentation (Swagger UI)

### Description
This PR adds the real version number from the backend to the API docs. To accomplish this easily, the `ServerVersion` class is extended by a new field `fullString` that contains a pre-calculated string representation of the version parts.

Next, the paths of the API docs were slightly changed to be more similar to the actual API base URLs. The new routes are `/apidoc/v2` (for `/api/v2`) and `/apidoc/private` (for `/api/private`).

Finally, the Caddyfile has been extended to proxy the API docs from the backend server.

### Steps

- [x] Added implementation
- [x] I read the [contribution documentation](https://github.com/hedgedoc/hedgedoc/blob/develop/CONTRIBUTING.md) and
  made sure that:
  - My commits are signed-off to accept the DCO.
  - This PR targets the correct branch: `master` for 1.x & docs, `develop` for 2.x

### Related Issue(s)
none

2023-01-09 18:25 UTC, DerMolly approved these changes

2023-01-09 18:47 UTC, DerMolly requested changes
I tried this and apparently it does work for the backend (localhost:3000), but the caddy file does not work.

2023-01-09 19:08 UTC, mrdrogdrog commented
@DerMolly can't reproduce. works for me.

![OBJECTION!](https://i.gifer.com/origin/af/afd6e1f079817a240c017754f02875e1.gif)

<img width="902" alt="image" src="https://user-images.githubusercontent.com/6124140/211388008-d07fe1c0-53a1-4f71-9312-15ceceea93e4.png">

2023-01-09 19:09 UTC, mrdrogdrog approved these changes

2023-01-09 19:28 UTC, DerMolly approved these changes
Okay apparently something was very hung up. Restarted the laptop and now it works like it should.

2023-01-15 17:20 UTC, davidmehren approved these changes

2023-01-15 17:20 UTC, merged