config: Add a flag to control the /metrics and /status endpoints
hedgedoc/hedgedoc pull request #3219
Opened 2023-01-23 16:36 UTC by freesteph

### Component/Part
Application

### Description
It can be a security concern in some environments to expose system capabilities even though they don't expose any PII. Add a couple flags to control whether the `/metrics` and `/status` (and anything in the StatusRouter) are exposed.

### Steps

- [X] Added implementation
- [ ] Added / updated tests
- [X] Added / updated documentation
- [X] Added changelog snippet
- [X] I read the [contribution documentation](https://github.com/hedgedoc/hedgedoc/blob/develop/CONTRIBUTING.md) and
  made sure that:
  - My commits are signed-off to accept the DCO.
  - This PR targets the correct branch: `master` for 1.x & docs, `develop` for 2.x

### Related Issue(s)
https://github.com/hedgedoc/hedgedoc/issues/2574

2023-01-24 19:30 UTC, DerMolly requested changes

2023-01-24 19:30 UTC, DerMolly commented on docs/content/configuration.md
> +| `observability.exposeMetrics  | `CMD_OBSERVABILITY_EXPOSE_STATUS`  | **true** or `false`                                                                       | Controls whether the /status routes
```suggestion
| `observability.exposeStatus  | `CMD_OBSERVABILITY_EXPOSE_STATUS`  | **true** or `false`                                                                       | Controls whether the /status routes are exposed.                                                                                                                          |
```

2023-01-24 20:15 UTC, mrdrogdrog requested changes
Will approve as soon as docs are fixed

2023-01-24 20:27 UTC, freesteph commented
All done I believe. Thanks for looking into this!

2023-01-24 20:29 UTC, ErikMichelson requested changes
Two points:
- The config option is quite long with the term “observability” inside. In my opinion, `CMD_EXPOSE_METRICS` would be good enough.
- Having the status endpoint disabled, will break the [docker image's health check](https://github.com/hedgedoc/container/blob/master/resources/healthcheck.mjs). Therefore, I suggest that queries from localhost will always be allowed, no matter the config value.

2023-01-24 20:30 UTC, DerMolly approved these changes

2023-01-24 20:35 UTC, mrdrogdrog commented
Regarding the docker healthcheck we could use a new route that just returns "ok".

2023-01-25 12:47 UTC, freesteph commented
> Two points:
> 
>     * The config option is quite long with the term “observability” inside. In my opinion, `CMD_EXPOSE_METRICS` would be good enough. This is not very important to me, but I wanted to note it anyway.
> 
>     * Having the status endpoint disabled, will break the [docker image's health check](https://github.com/hedgedoc/container/blob/master/resources/healthcheck.mjs). Therefore, I suggest that queries from localhost will always be allowed, no matter the config value.

Thanks for the feedback. I think it makes sense to group these two options into an `observability` scope, it allows grouping them which is nice. Up to you though.

I've added a commit to keep `/status` returning 200, let me know if that's good enough.

2023-01-27 09:23 UTC, ErikMichelson approved these changes

2023-01-28 15:29 UTC, mrdrogdrog approved these changes

2023-01-29 19:09 UTC, InnayTool approved these changes

2023-01-31 09:26 UTC, merged