docs(SECURITY): Shift vulnerability reporting directly to GitHub
hedgedoc/hedgedoc pull request #3220
Opened 2023-01-23 20:33 UTC by SISheogorath

### Component/Part
SECURITY.md

### Description
This patch adjust the SECURITY.md to follow a new workflow, which results in reports ending up on GitHub without going through my mailbox, this frees resources on my side as well as reducing the bus factor.

Since most of the time, I do an editorial copy of the content of the E-Mail into GitHub's vulnerability template, this should help to reduce manual processes.

### Steps

- [x] Someone without admin rights on this repository should review that the steps work.
- [x] Added / updated documentation
- [x] I read the [contribution documentation](https://github.com/hedgedoc/hedgedoc/blob/develop/CONTRIBUTING.md) and
  made sure that:
  - My commits are signed-off to accept the DCO.
  - This PR targets the correct branch: `master` for 1.x & docs, `develop` for 2.x

2023-01-23 22:12 UTC, DerMolly requested changes

2023-01-23 22:12 UTC, DerMolly commented on SECURITY.md
> +allows to get in direct, but private contact with us. There is some more detailed
```suggestion
allows you to get in direct, but private contact with us. There is some more detailed
```

2023-01-23 22:53 UTC, DerMolly approved these changes

2023-01-24 10:41 UTC, ErikMichelson approved these changes

2023-01-24 19:07 UTC, merged