Replace remote cursors
hedgedoc/hedgedoc pull request #3270
Opened 2023-02-05 10:59 UTC by mrdrogdrog

### Component/Part
Frontend

### Description
This PR reworks the realtime communication

### Steps

- [ ] Added implementation
- [ ] Added / updated tests
- [ ] Added / updated documentation
- [ ] Added changelog snippet
- [ ] I read the [contribution documentation](https://github.com/hedgedoc/hedgedoc/blob/develop/CONTRIBUTING.md) and
  made sure that:
  - My commits are signed-off to accept the DCO.
  - This PR targets the correct branch: `master` for 1.x & docs, `develop` for 2.x

### Related Issue(s)

2023-03-16 16:01 UTC, ErikMichelson commented on frontend/src/components/editor-page/editor-pane/hooks/yjs/use-sync-realtime-users-to-code-mirror.ts
> +export const useSyncRealtimeUsersToCodeMirror = () => {
ESDoc

2023-03-16 16:46 UTC, mrdrogdrog commented on commons/src/y-doc-sync/y-doc-sync-client.ts
> +    doc.on('update', (update: Uint8Array, origin: unknown) => {
Yes. Because anything can be the origin. Also internal objects of yjs

2023-03-19 23:02 UTC, ErikMichelson requested changes

2023-03-20 09:27 UTC, mrdrogdrog commented on backend/src/realtime/realtime-note/realtime-note.spec.ts
>      const sut = new RealtimeNote(mockedNote, 'nothing');
That's a common abbreviation in testing and stands for "system under test". It is used to name the thing that you wanna test.

2023-03-20 15:41 UTC, mrdrogdrog commented on backend/src/realtime/realtime-note/realtime-user-status.ts
> +      username: displayName,
Not relevant. Display name is no cryptographical information.

2023-03-22 19:16 UTC, closed without merging