Refactor realtime-communication and replace y-protocols
hedgedoc/hedgedoc pull request #3584
Opened 2023-03-22 19:22 UTC by mrdrogdrog

### Component/Part
Realtime communication

### Description
This PR:
- refactors the whole realtime communication to work with json instead of binary and with events
- removes y-protocols
- removes y-codemirror.next and replaces it with an own plugin

### Steps

- [x] Added implementation
- [x] Added / updated tests
- [x] Added / updated documentation
- [x] I read the [contribution documentation](https://github.com/hedgedoc/hedgedoc/blob/develop/CONTRIBUTING.md) and
  made sure that:
  - My commits are signed-off to accept the DCO.
  - This PR targets the correct branch: `master` for 1.x & docs, `develop` for 2.x

### Related Issue(s)
Replaces #3270 because codecov didn't trigger correctly.

2023-03-23 20:18 UTC, mrdrogdrog commented on backend/src/realtime/realtime-note/realtime-user-status.spec.ts
> +      .withUsername('mock1')
Why? They're not used anywhere else.

2023-03-23 20:20 UTC, mrdrogdrog commented
Things that could be improved:
- Save/Cache the Y-Doc before deleting to preserve the structures and make re-syncs easier
- Cooldown before the realtime doc gets deleted

2023-03-23 20:25 UTC, mrdrogdrog commented on frontend/src/components/editor-page/editor-pane/codemirror-extensions/remote-cursors/cursor-colors.module.scss
> +.cursor-7 {
It's difficult to find more than 8 distinct colors. I would leave it like this for now and add more later.

2023-03-24 08:42 UTC, ErikMichelson requested changes
Only two docs things, nothing else left from my side

2023-03-24 08:42 UTC, ErikMichelson commented on frontend/src/components/editor-page/websocket-connection-modal/realtime-connection-modal.tsx
> +export const RealtimeConnectionModal: React.FC = () => {
```suggestion
/**
 * Modal with a spinner that is shown while reconnecting to the realtime backend
 */
export const RealtimeConnectionModal: React.FC = () => {
```

2023-03-24 08:42 UTC, ErikMichelson commented on frontend/src/components/editor-page/editor-pane/hooks/yjs/use-y-doc-sync-client-adapter.ts
> + * @param messageTransporter The {@link MessageTransporter message transporter} that sends and receive messages for the synchronisation
```suggestion
 * @param messageTransporter The {@link MessageTransporter message transporter} that sends and receives messages for the synchronisation
```

2023-03-24 13:06 UTC, merged