docs: add getting started guide
hedgedoc/hedgedoc pull request #3616
Opened 2023-03-24 16:50 UTC by davidmehren

<git@herrmehren.de>### Component/Part
docs

### Description
This PR adds a recommended Docker deployment and a getting started guide.

### Steps

- [x] Added / updated documentation
- [x] I read the [contribution documentation](https://github.com/hedgedoc/hedgedoc/blob/develop/CONTRIBUTING.md) and
  made sure that:
  - My commits are signed-off to accept the DCO.
  - This PR targets the correct branch: `master` for 1.x & docs, `develop` for 2.x

### Related Issue(s)
https://github.com/hedgedoc/hedgedoc/issues/3553

2023-03-24 19:02 UTC, DerMolly approved these changes

2023-03-25 09:51 UTC, DerMolly requested changes

2023-03-25 09:51 UTC, DerMolly commented on docker/.env
> +HD_SESSION_SECRET: "session_secret"
```suggestion
# Base settings
HD_BASE_URL="https://hedgedoc2.localhost"
HD_SESSION_SECRET: "session_secret"

# DB settings
HD_DATABASE_TYPE: "postgres"
HD_DATABASE_HOST: "db"
HD_DATABASE_PORT: "5432"
HD_DATABASE_NAME: "hedgedoc"
HD_DATABASE_USER: "hedgedoc"
HD_DATABASE_PASS: "password"
```

2023-03-25 09:51 UTC, DerMolly commented on docker/docker-compose.yml
> +# SPDX-FileCopyrightText: 2022 The HedgeDoc developers (see AUTHORS file)
```suggestion
# SPDX-FileCopyrightText: 2023 The HedgeDoc developers (see AUTHORS file)
```

2023-03-25 10:05 UTC, ErikMichelson commented on docker/.env
> +HD_AUTH_LOCAL_ENABLE_REGISTER: "true"
```suggestion
HD_SESSION_SECRET="session_secret"

# Database settings
HD_DATABASE_TYPE="postgres"
HD_DATABASE_HOST="db"
HD_DATABASE_PORT="5432"
HD_DATABASE_NAME="hedgedoc"
HD_DATABASE_USER="hedgedoc"
HD_DATABASE_PASS="password"

# Uploads
HD_MEDIA_BACKEND="filesystem"
HD_MEDIA_BACKEND_FILESYSTEM_UPLOAD_PATH="uploads/"

# Auth
HD_AUTH_LOCAL_ENABLE_LOGIN="true"
HD_AUTH_LOCAL_ENABLE_REGISTER="true"
```

2023-03-25 10:08 UTC, ErikMichelson approved these changes

2023-03-25 11:41 UTC, DerMolly approved these changes

2023-03-25 11:58 UTC, mrdrogdrog approved these changes

2023-03-25 12:05 UTC, InnayTool approved these changes

2023-03-25 12:05 UTC, merged