Is owner
hedgedoc/hedgedoc pull request #3618
Opened 2023-03-24 17:24 UTC by DerMolly

### Component/Part
isOwner

### Description
This PR add the isOwner hook and deactivates different buttons and textfields if the user is not the owner…

### Steps

- [x] Added implementation
- [x] I read the [contribution documentation](https://github.com/hedgedoc/hedgedoc/blob/develop/CONTRIBUTING.md) and
  made sure that:
  - My commits are signed-off to accept the DCO.
  - This PR targets the correct branch: `master` for 1.x & docs, `develop` for 2.x

2023-03-24 18:35 UTC, ErikMichelson commented on frontend/src/hooks/common/use-is-owner.ts
> + */
Docs wrong

2023-03-24 18:43 UTC, ErikMichelson approved these changes

2023-03-25 09:44 UTC, mrdrogdrog requested changes

2023-03-25 09:44 UTC, mrdrogdrog commented on frontend/src/hooks/common/use-is-owner.ts
> +  return useMemo(() => owner === me, [owner, me])
So if a guest has created the doc and I'm not logged in, i'm the owner?

2023-03-25 10:31 UTC, mrdrogdrog requested changes
`@hedgedoc/frontend:test:e2e:ci:      CypressError: Timed out retrying after 15050ms: `cy.click()` failed because this element is `disabled`:`

2023-03-25 11:48 UTC, ErikMichelson approved these changes

2023-03-25 11:59 UTC, mrdrogdrog approved these changes

2023-03-25 11:59 UTC, merged