Cleanup .env configs
hedgedoc/hedgedoc pull request #3632
Opened 2023-03-25 15:25 UTC by davidmehren

### Component/Part
Configuration

### Description
This PR merges various .env config file into one file in the repo root and splits the configuration of the frontend & backend listen ports into two variables.

### Steps

- [ ] Added implementation
- [ ] Added / updated tests
- [ ] Added / updated documentation
- [ ] Added changelog snippet
- [ ] I read the [contribution documentation](https://github.com/hedgedoc/hedgedoc/blob/develop/CONTRIBUTING.md) and
  made sure that:
  - My commits are signed-off to accept the DCO.
  - This PR targets the correct branch: `master` for 1.x & docs, `develop` for 2.x

### Related Issue(s)

2023-03-25 17:35 UTC, InnayTool approved these changes

2023-03-25 17:59 UTC, DerMolly approved these changes

2023-03-26 08:21 UTC, mrdrogdrog approved these changes

2023-03-26 08:32 UTC, ErikMichelson commented on docs/content/config/index.md
> +HD_SESSION_SECRET="session_secret"
```suggestion
HD_SESSION_SECRET="change_me_in_production"
```

2023-03-26 08:32 UTC, ErikMichelson commented on docs/content/config/index.md
Add that this requires own configuration adjustments to the reverse proxy (so that it serves the frontend at two domains)

2023-03-26 10:28 UTC, ErikMichelson approved these changes

2023-03-26 10:46 UTC, DerMolly requested changes
As .env.production is removed this breaks the netlify deployment action

2023-03-26 13:53 UTC, merged