feat: check permissions in realtime code and frontend
hedgedoc/hedgedoc pull request #3643
Opened 2023-03-26 13:43 UTC by DerMolly

### Component/Part

### Description
This PR fixes/adds/improves/...

### Steps

- [ ] Added implementation
- [ ] Added / updated tests
- [ ] Added / updated documentation
- [ ] Added changelog snippet
- [ ] I read the [contribution documentation](https://github.com/hedgedoc/hedgedoc/blob/develop/CONTRIBUTING.md) and
  made sure that:
  - My commits are signed-off to accept the DCO.
  - This PR targets the correct branch: `master` for 1.x & docs, `develop` for 2.x

### Related Issue(s)

2023-03-29 13:51 UTC, ErikMichelson requested changes

2023-03-29 13:51 UTC, ErikMichelson commented on commons/src/utils/permissions.ts
> +
```suggestion

/**
 * Checks if the given user is the owner of a note.
 *
 * @param permissions The permissions of the note to check
 * @param user The username of the user
 * @return True if the user is the owner of the note
 */
```

2023-03-29 13:51 UTC, ErikMichelson commented on commons/src/utils/permissions.ts
> +export const userCanEdit = (permissions: NotePermissions, user?: string) => {
```suggestion
/**
 * Checks if the given user may edit a note.
 *
 * @param permissions The permissions of the note to check
 * @param user The username of the user
 * @return True if the user has the permission to edit the note
 */
export const userCanEdit = (permissions: NotePermissions, user?: string): boolean => {
```

2023-03-29 13:51 UTC, ErikMichelson commented on commons/src/utils/permissions.ts
> +  )
This checks for `!!user` in every iteration of the loop that runs over the sharedToGroups array. You could change this to the following:

```suggestion
  const mayWriteViaGroupPermission = !!user && permissions.sharedToGroups.some(
    (value) =>
      value.groupName === SpecialGroup.LOGGED_IN && value.canEdit
  )
```

2023-03-29 19:46 UTC, ErikMichelson requested changes

2023-03-29 19:46 UTC, ErikMichelson commented on commons/src/utils/permissions.ts
> +export const userCanEdit = (permissions: NotePermissions, user?: string) => {
The boolean return type is still missing

2023-04-04 18:07 UTC, mrdrogdrog commented
Well depends. Should they see the other people cursors or not? Because that's coupled.

2023-04-04 19:25 UTC, DerMolly commented
I think they should. Other people should not see the cursor of the read-only user, but the read-only users should see what happens in the pad.

2023-04-05 11:00 UTC, mrdrogdrog approved these changes

2023-04-06 20:53 UTC, ErikMichelson approved these changes

2023-04-06 20:54 UTC, merged