improve realtime tests
hedgedoc/hedgedoc pull request #3712
Opened 2023-03-31 20:17 UTC by mrdrogdrog

### Component/Part
backend realtime tests 

### Description
This PR refactors some realtime tests and utils.

### Steps

- [x] Added implementation
- [x] Added / updated tests
- [x] I read the [contribution documentation](https://github.com/hedgedoc/hedgedoc/blob/develop/CONTRIBUTING.md) and
  made sure that:
  - My commits are signed-off to accept the DCO.
  - This PR targets the correct branch: `master` for 1.x & docs, `develop` for 2.x

2023-04-01 11:55 UTC, DerMolly requested changes

2023-04-01 11:55 UTC, DerMolly commented on backend/src/realtime/realtime-note/realtime-user-status-adapter.spec.ts
> +    sendMessageSource = spyOnSendMessage(clientSource);
I think these names are a bit confusing. Maybe we should either use `sendMessageSourceClient` or `clientSourceSendMessage`?

2023-04-01 11:55 UTC, DerMolly commented on backend/src/realtime/realtime-note/realtime-user-status-adapter.spec.ts
> +      .withGuestUser('Virtuous Mockingbird')
I think it's not the worst idea to extract this string.

2023-04-01 16:30 UTC, DerMolly approved these changes

2023-04-04 16:28 UTC, ErikMichelson approved these changes

2023-04-04 16:29 UTC, merged