Only show non-guest users in the sidebar
hedgedoc/hedgedoc pull request #3813
Opened 2023-04-15 12:21 UTC by GGH-WeyboZetO

### Component/Part
Frontend

### Description
Only show non-guest users in the sidebar

### Steps
- [x] Added implementation
- [x] I read the [contribution documentation](https://github.com/hedgedoc/hedgedoc/blob/develop/CONTRIBUTING.md) and
  made sure that:
  - My commits are signed-off to accept the DCO.
  - This PR targets the correct branch: `develop` for 2.x
  - Signed-off-by: Shan Michel <yuplasmas@gmail.com>

### Related Issue(s)
#2953

2023-04-15 12:38 UTC, mrdrogdrog commented
Hello,

thanks for your contribution, but I guess you misunderstood something here. With "sidebar" @ErikMichelson meant the sidebar in the revisions dialog. Or in other words: Don't list the guest users in the list items.

While this would be the easiest solution, it isn't the preferred one. The alternative in an issue should only be implemented if the requested feature/improvement is not possible.

2023-04-15 17:10 UTC, GGH-WeyboZetO commented
Hello,

I think I understand now what he meant now.
![REvision](https://user-images.githubusercontent.com/93222701/232240005-46edde2b-0742-410c-90e2-f6f5226180b9.png)
I'm doing my tests with yarn start:dev with localhost but I don't see any "mock icon" like that:
![hw](https://user-images.githubusercontent.com/93222701/232240363-0635a831-f8dd-47e8-b087-bf2c68f736aa.png)
How can I get something similar with 1-2 mock icons or have that feature not been deleted?
The issue is to get the name of the user displayed when we hover our mouse over the icon right?

Thank you.

2023-04-15 17:39 UTC, mrdrogdrog commented
> I'm doing my tests with yarn start:dev with localhost but I don't see any "mock icon" like that:

that's because the backend doesn't save author information right now. It simply just doesn't know who edited what. 

>  or have that feature not been deleted

You can't. if you run the frontend in mock mode then there is NO data persistence. If you need other data then you have to change the mock data in `src/pages/api/private/notes/feature/revisions/`.


> The issue is to get the name of the user displayed when we hover our mouse over the icon right

No. That is already working. The original issue #2953 is about showing how many guest users have participated in a revision.

2023-04-15 18:18 UTC, GGH-WeyboZetO commented
I tried to git grep "revisions" and got that result but since it's a frontend issue I guess none of them are right since they are all backend.
![grepdd](https://user-images.githubusercontent.com/93222701/232246687-0bab7fa1-0a18-4f9b-b4af-d3a80d4688a3.png)
Can I ask where exactly is located the done doing thoses boxes?
![lcasx](https://user-images.githubusercontent.com/93222701/232246702-2834bc87-375d-4f80-9d1e-b3f8169daf7b.png)

2023-04-15 18:56 UTC, GGH-WeyboZetO commented
![modifnombreauteur](https://user-images.githubusercontent.com/93222701/232248344-e1671770-ba6d-4cb6-9b15-30104e4c7ba2.png)

2023-04-16 07:58 UTC, mrdrogdrog requested changes
Please squash your commits.

2023-04-16 07:58 UTC, mrdrogdrog commented on frontend/src/components/editor-page/document-bar/revisions/revision-list-entry.tsx
> +        <Trans i18nKey={'Number of author'} />: {revision.anonymousAuthorCount}
We don't use actual sentences as i18n keys but fqdn like in line 69.

2023-04-16 11:04 UTC, closed without merging