refactor app bar
hedgedoc/hedgedoc pull request #3878
Opened 2023-04-24 01:03 UTC by ErikMichelson

### Component/Part
layout -> app bar

### Description
This PR replaces the existing app bar with a layout similar to the design proposal.

### Steps

- [ ] Added implementation
- [ ] Added / updated tests
- [ ] Added / updated documentation
- [ ] Added changelog snippet
- [ ] I read the [contribution documentation](https://github.com/hedgedoc/hedgedoc/blob/develop/CONTRIBUTING.md) and
  made sure that:
  - My commits are signed-off to accept the DCO.
  - This PR targets the correct branch: `master` for 1.x & docs, `develop` for 2.x

### Related Issue(s)

2023-06-30 11:16 UTC, DerMolly commented on frontend/src/components/layout/app-bar/app-bar-elements/note-title-element/note-title-element.tsx
> +        <span className={`text-secondary ${styles['read-only-marker']}`}>read-only</span>
This should probably be translated…

2023-06-30 20:56 UTC, DerMolly approved these changes

2023-07-01 20:02 UTC, mrdrogdrog requested changes

2023-07-01 20:02 UTC, mrdrogdrog commented on frontend/src/components/global-dialogs/shortcuts-modal/shortcuts-modal.tsx
> +export const ShortcutsModal: React.FC<ModalVisibilityProps> = ({ show, onHide }) => {
docs missing

2023-07-02 15:45 UTC, mrdrogdrog approved these changes

2023-07-02 15:54 UTC, merged