fix(frontend): readOnly permits codemirror select text
hedgedoc/hedgedoc pull request #4291
Opened 2023-06-23 11:49 UTC by Avi98

### Component/Part
Frontend

### Description
This PR fixes #3754

### Steps

- [x] Added implementation
- [ ] Added / updated tests
- [ ] Added / updated documentation
- [ ] Added changelog snippet
- [x] I read the [contribution documentation](https://github.com/hedgedoc/hedgedoc/blob/develop/CONTRIBUTING.md) and
  made sure that:
  - My commits are signed-off to accept the DCO.
  - This PR targets the correct branch: `master` for 1.x & docs, `develop` for 2.x

2023-06-23 18:02 UTC, mrdrogdrog requested changes

2023-06-26 23:54 UTC, ErikMichelson approved these changes

2023-06-27 05:43 UTC, mrdrogdrog approved these changes

2023-06-27 05:43 UTC, mrdrogdrog commented
Please solve the conflicts

2023-06-28 07:06 UTC, merged

2023-06-28 07:06 UTC, mrdrogdrog commented
Thank you for your contribution ❤️