chore(dependency) add flexsearch-ts
hedgedoc/hedgedoc pull request #4298
Opened 2023-06-24 13:16 UTC by DerMolly

### Component/Part
Cheatsheet

### Description
This PR adds a search to the cheatsheet

### Steps

- [x] Added implementation
- [ ] Added / updated tests
- [x] I read the [contribution documentation](https://github.com/hedgedoc/hedgedoc/blob/develop/CONTRIBUTING.md) and
  made sure that:
  - My commits are signed-off to accept the DCO.
  - This PR targets the correct branch: `master` for 1.x & docs, `develop` for 2.x

### Related Issue(s)
#3656

2023-06-24 16:41 UTC, mrdrogdrog requested changes
First batch

2023-06-24 16:41 UTC, mrdrogdrog commented on frontend/package.json
> +    "@testing-library/react-hooks": "^8.0.1",
Pin

2023-06-24 16:41 UTC, mrdrogdrog commented on frontend/src/hooks/common/use-document-search.spec.ts
> +import { act, renderHook } from '@testing-library/react'
Clean import

2023-06-24 16:41 UTC, mrdrogdrog commented on frontend/src/components/editor-page/app-bar/cheatsheet/cheatsheet-search.tsx
> +      }
You can avoid the memo if you define it outside of the function

2023-06-24 16:41 UTC, mrdrogdrog commented on frontend/src/components/editor-page/app-bar/cheatsheet/cheatsheet-search.tsx
> +export const CheatsheetSearch: React.FC<CheatsheetSearchProps> = ({ setExtensions }) => {
Docs missing

2023-06-25 19:29 UTC, mrdrogdrog requested changes

2023-06-25 19:29 UTC, mrdrogdrog commented on frontend/src/components/editor-page/app-bar/cheatsheet/cheatsheet-search.tsx
> +        <X />
Wrap the icon in an UiIcon

2023-06-25 19:29 UTC, mrdrogdrog commented on frontend/src/components/editor-page/app-bar/cheatsheet/cheatsheet-search.tsx
> +  const cheatsheets = useMemo(() => allAppExtensions.flatMap((extension) => extension.buildCheatsheetExtensions()), [])
```suggestion
  const cheatsheetExtensions = useMemo(() => allAppExtensions.flatMap((extension) => extension.buildCheatsheetExtensions()), [])
```

2023-06-25 19:34 UTC, mrdrogdrog commented
![image](https://github.com/hedgedoc/hedgedoc/assets/6124140/e843355d-3f80-411b-bd51-53c442894554)

should we add the code to the index?

2023-06-25 19:40 UTC, DerMolly commented
> ![image](https://user-images.githubusercontent.com/6124140/248583161-e843355d-3f80-411b-bd51-53c442894554.png)
> 
> should we add the code to the index?

Not a bad idea. I added this…

2023-06-25 20:27 UTC, mrdrogdrog requested changes
Minor stuff :shrug:

2023-06-25 20:27 UTC, mrdrogdrog commented on frontend/src/components/editor-page/app-bar/cheatsheet/cheatsheet-search.tsx
> +  const results = useDocumentSearch(cheatsheetSearchIndexEntries, searchOptions, searchTerm)
```suggestion
  const searchResults = useDocumentSearch(cheatsheetSearchIndexEntries, searchOptions, searchTerm)
```

2023-06-26 17:08 UTC, mrdrogdrog approved these changes

2023-06-26 23:59 UTC, ErikMichelson requested changes
Search does only work for cheatsheet entries that do not have "topics".
For example try searching for "headline" or "code" and you won't find the relevant section from the "basics" category.

2023-06-29 13:17 UTC, ErikMichelson requested changes

2023-06-29 13:17 UTC, ErikMichelson commented on frontend/src/components/editor-page/app-bar/cheatsheet/cheatsheet-search.tsx
> +        aria-label={t('cheatsheet.search') ?? undefined}
These should probably use the `useTranslatedText` hook.

2023-06-29 13:17 UTC, ErikMichelson commented on frontend/src/components/editor-page/app-bar/cheatsheet/cheatsheet-search.tsx
> +  })
This can be simplified.

```suggestion
  const onChange = useOnInputChange(setSearchTerm)
```

2023-07-02 12:57 UTC, mrdrogdrog requested changes

2023-07-02 12:57 UTC, mrdrogdrog commented on frontend/src/components/editor-page/app-bar/cheatsheet/cheatsheet-search.tsx
> +  const buildSearchIndexDocument = useCallback(
If I get the terminology right then you're not building documents, but entries.

2023-07-02 13:21 UTC, mrdrogdrog approved these changes

2023-07-02 14:36 UTC, ErikMichelson approved these changes

2023-07-02 14:38 UTC, merged