build(backend): add nestjs-typed eslint plugin
hedgedoc/hedgedoc pull request #4304
Opened 2023-06-25 17:37 UTC by davidmehren

Signed-off-by: David Mehren <git@herrmehren.de>### Component/Part

### Description
This PR configures https://github.com/darraghoriordan/eslint-plugin-nestjs-typed to add some NextJS linting rules

### Steps

- [x] Added implementation
- [x] I read the [contribution documentation](https://github.com/hedgedoc/hedgedoc/blob/develop/CONTRIBUTING.md) and
  made sure that:
  - My commits are signed-off to accept the DCO.
  - This PR targets the correct branch: `master` for 1.x & docs, `develop` for 2.x

### Related Issue(s)

2023-06-25 18:27 UTC, mrdrogdrog requested changes

2023-06-25 18:27 UTC, mrdrogdrog commented on backend/package.json
> +    "@darraghor/eslint-plugin-nestjs-typed": "^3.22.6",
Pin

2023-06-26 22:39 UTC, DerMolly approved these changes

2023-06-26 23:06 UTC, ErikMichelson approved these changes

2023-07-09 19:12 UTC, mrdrogdrog approved these changes

2023-07-09 19:12 UTC, merged