Increase Frontend Performance
hedgedoc/hedgedoc pull request #4398
Opened 2023-07-05 19:36 UTC by mrdrogdrog

### Component/Part
Renderer

### Description
This PR increases the performance of the frontend by using `useDeferredValue`. It's a new hook in React 18 and renders a state change in the background and only renders the result if the browser can handle it right now. If the value changes quickly and often then the result is that not every change is visible.

It also adds performance markers to measure how long the frontend needs to render a markdown text.

### Steps

- [x] Added implementation
- [x] I read the [contribution documentation](https://github.com/hedgedoc/hedgedoc/blob/develop/CONTRIBUTING.md) and
  made sure that:
  - My commits are signed-off to accept the DCO.
  - This PR targets the correct branch: `master` for 1.x & docs, `develop` for 2.x

2023-07-05 22:26 UTC, ErikMichelson approved these changes

2023-07-05 22:28 UTC, ErikMichelson requested changes
`Error: Uncaught [TypeError: performance.mark is not a function]` in jest 👀

2023-07-06 08:11 UTC, ErikMichelson approved these changes

2023-07-06 08:39 UTC, DerMolly approved these changes

2023-07-06 08:44 UTC, merged