fix(oauth2): Fix crash in rolesClaim extraction
hedgedoc/hedgedoc pull request #4757
Opened 2023-08-30 23:59 UTC by SISheogorath

### Component/Part
auth/oauth2

### Description
This patch adds a try-catch around the rolesClaim extraction to prevent full crashes of HedgeDoc when a user profile is read, that doesn't contain any such claim, which can happen with some IdPs, like Keycloak, that omit the attribute when it's empty.

As a result an authorized user would crash the entire server, which is definitely unintended behaviour. The simply try-catch should resolve the issue and make sure that roles is always defined even if the `extractProfileAttribute` call fails.

### Steps

- [x] Added implementation
- [ ] Added changelog snippet
- [x] I read the [contribution documentation](https://github.com/hedgedoc/hedgedoc/blob/develop/CONTRIBUTING.md) and
  made sure that:
  - My commits are signed-off to accept the DCO.
  - This PR targets the correct branch: `master` for 1.x & docs, `develop` for 2.x

2023-09-10 18:46 UTC, davidmehren approved these changes

2023-09-10 18:56 UTC, mrdrogdrog requested changes

2023-09-10 18:56 UTC, mrdrogdrog commented on lib/web/auth/oauth2/index.js
> +      }
Please add a return in the catch block

2023-10-16 12:58 UTC, ErikMichelson commented
@SISheogorath What's the state with this PR? :)

2023-10-16 13:05 UTC, SISheogorath commented
Looks like I missed the remark, otherwise it should be good to go :)

2023-10-16 14:49 UTC, SISheogorath commented on lib/web/auth/oauth2/index.js
> +      }
done :)

2023-10-16 23:03 UTC, ErikMichelson approved these changes

2023-10-19 17:34 UTC, mrdrogdrog approved these changes

2023-10-19 17:34 UTC, merged