Add button to re-open motd
hedgedoc/hedgedoc pull request #4781
Opened 2023-09-04 14:21 UTC by ErikMichelson

### Component/Part
frontend -> app bar -> help menu

### Description
This PR adds a button to the help menu to re-open the motd.
To accomplish this, the MotdModal component has been refactored to allow being force-shown. The modal content is also cached in local storage as on the HEAD request no content will be delivered.

### Steps

- [x] Added implementation
- [x] Added / updated tests
- [x] I read the [contribution documentation](https://github.com/hedgedoc/hedgedoc/blob/develop/CONTRIBUTING.md) and
  made sure that:
  - My commits are signed-off to accept the DCO.
  - This PR targets the correct branch: `master` for 1.x & docs, `develop` for 2.x

### Related Issue(s)
Closes #2933

2023-09-04 14:27 UTC, mrdrogdrog requested changes

2023-09-04 14:27 UTC, mrdrogdrog commented on frontend/src/components/global-dialogs/motd-modal/motd-modal.tsx
>      }
```suggestion
    onDismiss?.()
```

2023-09-04 14:27 UTC, mrdrogdrog commented on frontend/src/components/global-dialogs/motd-modal/use-motd-message.ts
> + * Reads the motd from the global application state.
Wrong.

2023-09-10 18:26 UTC, mrdrogdrog commented
Changed to Draft because @ErikMichelson wanted to change stuff

2023-10-14 00:24 UTC, ErikMichelson commented
Integrated in #5123

2023-10-14 00:24 UTC, closed without merging