feat(api/notes): prevent creating new notes with alias equal to an existing note ID
hedgedoc/hedgedoc pull request #4829
Opened 2023-09-10 20:07 UTC by davidmehren

### Component/Part
notes service

### Description
This PR adds a check to `createNote` to prevent creating new notes with an alias equal to an existing note ID.

### Steps

- [x] Added implementation
- [x] Added / updated tests
- [x] I read the [contribution documentation](https://github.com/hedgedoc/hedgedoc/blob/develop/CONTRIBUTING.md) and
  made sure that:
  - My commits are signed-off to accept the DCO.
  - This PR targets the correct branch: `master` for 1.x & docs, `develop` for 2.x

### Related Issue(s)

2023-09-10 20:20 UTC, ErikMichelson requested changes

2023-09-10 20:20 UTC, ErikMichelson commented on backend/src/notes/notes.service.ts
> +        `A note with the alias '${noteId}' already exists.`,
This is misleading and seems to be an implementation error. The method does only check publicIds and internal ids(?) but not aliases.

2023-09-11 10:01 UTC, InnayTool commented on backend/src/notes/notes.service.ts
>        this.checkNoteIdOrAlias(alias);
since we have multiple check methods. We should rename this so it is more obvious what is checked.

2024-04-18 18:55 UTC, DerMolly approved these changes

2024-04-18 20:15 UTC, merged