enhancement(notifications): remove from state after dismissal
hedgedoc/hedgedoc pull request #5125
Opened 2023-10-14 01:39 UTC by ErikMichelson

### Component/Part
UI Notifications

### Description
Notifications will be removed from the state after dismissal.
This PR changes the implementation from an array to a Map, as that makes accessing a notification for dismissal or removal more performant.

### Steps

- [x] Added implementation
- [x] I read the [contribution documentation](https://github.com/hedgedoc/hedgedoc/blob/develop/CONTRIBUTING.md) and
  made sure that:
  - My commits are signed-off to accept the DCO.
  - This PR targets the correct branch: `master` for 1.x & docs, `develop` for 2.x

### Related Issue(s)
fixes #4948

2023-10-14 09:27 UTC, mrdrogdrog requested changes

2023-10-14 09:27 UTC, mrdrogdrog commented on frontend/src/components/notifications/ui-notification-boundary.tsx
> +    return Object.values(uiNotifications)
i'm not sure how order-safe `Object.values` is. Please sort the notifications by date.

2023-10-15 18:39 UTC, DerMolly approved these changes

2023-10-15 19:05 UTC, mrdrogdrog approved these changes

2023-10-15 19:08 UTC, merged