feat: added tls config
hedgedoc/hedgedoc pull request #5530
Opened 2024-03-06 06:24 UTC by Avi98

### Component/Part
backend -> Database cofig 

### Description
This PR fixes 3063

### Steps

- [x] Added implementation
- [ ] Added / updated tests
- [x] Added / updated documentation
- [ ] Added changelog snippet
- [x] I read the [contribution documentation](https://github.com/hedgedoc/hedgedoc/blob/develop/CONTRIBUTING.md) and
  made sure that:
  - My commits are signed-off to accept the DCO.
  - This PR targets the correct branch: `master` for 1.x & docs, `develop` for 2.x

2024-03-06 18:06 UTC, ErikMichelson requested changes, later dismissed
Thanks for your contribution!

I haven't tested the code yet, these are just some things I saw when having a look at the code.

2024-03-06 18:06 UTC, ErikMichelson commented on docs/content/references/config/database.md
> +| `HD_DATABASE_SSL_CA`                  | -       | string | The SSL/TLS certificate key needed for database connection.                                                   |
Maybe specify more concrete: Do you pass the file name of the CA certificate or do you pass the contents (and if so in which encoding)?

Please state that this certificate (as every CA cert) is the anchor for checking the validity of the cert chain.

2024-03-06 18:06 UTC, ErikMichelson commented on docs/content/references/config/database.md
> +| `HD_DATABASE_SSL_CERT`                | -       | string | The client certificate to use in the SSL handshake                                                            |
Same as for the CA certificate.

2024-03-08 12:46 UTC, Avi98 commented
> Thanks for your contribution!
> 
> I haven't tested the code yet, these are just some things I saw when looking at the code.

Erik, I have added an env flag `HD_DATABASE_SSL` for validating the SSL/TLS config. If the flag is absent, the SSL/TLS joi validation will not work. 


| environment variable | default | example          | description                                                                                |
| -------------------- | ------- | ---------------- | ------------------------------------------------------------------------------------------ |
| `HD_DATABASE_SSL`    | '0'     | `1`              | Pass this value when SSL/TLS configuration is needed                                      |

Tested joi validation for following condition
1. When `HD_DATABASE_SSL=1`  & `HD_DATABASE_TYPE=postgres` SSL/TLS env config for postgres should be present.  
2. When `HD_DATABASE_SSL=1`  & `HD_DATABASE_TYPE=mysql` SSL/TLS env config SSL/TLS for mysql/Mariadb should be present. 
3. `HD_DATABASE_SSL` is not there (backward compatible) SSL/TLS validation is not added 

https://github.com/hedgedoc/hedgedoc/assets/26133749/088843ea-355b-4054-833f-4c5992518668

2024-03-13 12:57 UTC, ErikMichelson reviewed
This gets in the right direction! :)

What still surprises me is the reason we need completely separate environment variables for postgres and maraidb/mysql? I get that you intended to make explicit which options are only relevant for the chosen database type. But having for example both `HD_SQL_SSL_CA_PATH` and `HD_PG_SSL_CA_PATH` seems a bit unnecessary to me. For changing that the code doesn't need greater changes, it's more a thing of renaming the variables and updating the documentation.

2024-03-13 12:57 UTC, ErikMichelson commented on backend/src/config/database.config.ts
> +};
As this method is rather crucial to database security options, it should be unit-tested. The `getSecret` method could be mocked for that.

2025-01-09 08:43 UTC, sndrsmnk commented
I was looking for (PostgreSQL) TLS/SSL support in Hedgedoc when i found this. Any update on this progressing?
Thanks for the work!!

2026-03-06 13:20 UTC, FAUSheppy commented
Lovely people what's the status/holdup here? Is it just the unit test?

2026-04-09 21:00 UTC, DerMolly approved these changes

2026-04-09 21:04 UTC, merged