docs: add google cloud storage bucket guide
hedgedoc/hedgedoc pull request #5557
Opened 2024-04-09 10:06 UTC by syphernl

### Component/Part
Documentation

### Description
This PR adds a guide on how to setup the S3 integration with Google Cloud Storage

### Steps

- [ ] Added implementation
- [ ] Added / updated tests
- [X] Added / updated documentation
- [ ] Added changelog snippet
- [ ] I read the [contribution documentation](https://github.com/hedgedoc/hedgedoc/blob/develop/CONTRIBUTING.md) and
  made sure that:
  - My commits are signed-off to accept the DCO.
  - This PR targets the correct branch: `master` for 1.x & docs, `develop` for 2.x

### Related Issue(s)
Closes #5541

2024-04-18 18:56 UTC, DerMolly commented
Hey @syphernl,
thanks for your contribution!

In order to get this merged, we need you to sign-off your commits according to the contribution guidelines for the HedgeDoc organization. You can find more information on this here: https://github.com/hedgedoc/hedgedoc/blob/develop/CONTRIBUTING.md#certificate-of-origin

2024-08-28 18:39 UTC, ErikMichelson requested changes
Sorry, this PR got lost in the amount of other PRs. 
Thanks for your contribution!

In general, it looks good, however as you're updating docs for current HedgeDoc 1.x, please use the HedgeDoc 1.x config environment variables.

2024-08-28 18:39 UTC, ErikMichelson commented on docs/content/guides/s3-google-cloud-storage.md
> +HD_MEDIA_BACKEND_S3_BUCKET="your-bucket-name"
```suggestion
Set the following environment variables (or the [corresponding config.json values](/configuration/#amazon-s3)):

```env
CMD_IMAGE_UPLOAD_TYPE="s3"
CMD_S3_ENDPOINT="https://storage.googleapis.com"
CMD_S3_ACCESS_KEY_ID="GOOG1EXXXXXXXXXX"
CMD_S3_SECRET_ACCESS_KEY="XXXXXXXXXX"
CMD_S3_BUCKET="your-bucket-name"
```

2024-08-28 18:39 UTC, ErikMichelson commented on docs/mkdocs.yml
> +          - Google Cloud Storage Buckets: guides/s3-google-cloud-storage.md
That's shorter and precise enough

```suggestion
          - Google Cloud Storage: guides/s3-google-cloud-storage.md
```

2024-08-28 18:48 UTC, ErikMichelson approved these changes

2024-08-28 19:41 UTC, merged