Add templates for issues and PRs
hedgedoc/hedgedoc pull request #568
Opened 2020-11-12 18:41 UTC by jfowl

Shamelessly <del>stolen</del> inspired from the react client repo.

2020-11-13 16:42 UTC, InnayTool approved these changes

2020-11-13 16:50 UTC, davidmehren requested changes

2020-11-13 16:50 UTC, davidmehren commented on .github/ISSUE_TEMPLATE/feature_request.md
> +labels: 'feature'
```suggestion
labels: 'feature request'
```

2020-11-13 16:50 UTC, davidmehren commented on .github/ISSUE_TEMPLATE/bug_report.md
> +about: Create a report to help us improve
```suggestion
about: Create a report to help us improve HedgeDoc.
```

2020-11-15 11:06 UTC, davidmehren approved these changes

2020-11-15 11:06 UTC, merged