refactor(backend): rename auth to public-auth-token
hedgedoc/hedgedoc pull request #5774
Opened 2024-09-01 13:05 UTC by InnayTool

### Component/Part

### Description
This PR fixes/adds/improves/...

### Steps

- [ ] Added implementation
- [ ] Added / updated tests
- [ ] Added / updated documentation
- [ ] Added changelog snippet
- [x] I read the [contribution documentation](https://github.com/hedgedoc/hedgedoc/blob/develop/CONTRIBUTING.md) and
  made sure that:
  - My commits are signed-off to accept the DCO.
  - This PR targets the correct branch: `master` for 1.x & docs, `develop` for 2.x

### Related Issue(s)

2024-09-01 17:34 UTC, DerMolly requested changes

2024-09-01 17:34 UTC, DerMolly commented on backend/src/public-auth-token/mock-auth.guard.ts
This could be named in accordance to `PublicAuthTokenGuard`

2024-09-01 23:03 UTC, ErikMichelson requested changes

2024-09-01 23:03 UTC, ErikMichelson commented on backend/src/public-auth-token/public-auth-token.service.ts
> +      validUntil = maximumTokenValidity;
Do not override params! (Any always use brackets around if bodies)

```suggestion
    const validUntilLimited = !validUntil || validUntil === 0 || validUntil > maximumTokenValidity ? maximumTokenValidity : validUntil;
```

2024-09-01 23:03 UTC, ErikMichelson commented on backend/src/public-auth-token/public-auth-token.service.ts
> +      new Date(validUntil),
In accordance with the former

```suggestion
      new Date(validUntilLimited),
```

2024-09-02 08:29 UTC, ErikMichelson approved these changes

2024-09-02 08:29 UTC, DerMolly approved these changes

2024-09-02 08:33 UTC, merged