Move docs into subdirectory to make structor work
hedgedoc/hedgedoc pull request #656
Opened 2021-01-04 21:53 UTC by mrdrogdrog

### Component/Part
Documentation

### Description
This PR moves the hole documentation files into a subdirectory that is in docs. Why?
Mkdocs can't build documentations for multiple versions. That's where structor comes in place. It checks out branches of a repository, builds the docs with mkdocs for this branch and patches the results together.
Structors looks for a requirements.txt file in every branch it processed. The requirements.txt includes every dependency that is needed by mkdocs (like themes, extension) to build the documentation for this branch.
And here comes the problem: The requirements.txt MUST be next to the mkdocs.yml. And structors searches for the mkdocs.yml in two places. In the root and in docs/.
So okay. Why don't we just let it like it was and move the requirements.txt and the mkdocs.yml into the docs folder? Easy answer: Because mkdocs wants the configuration (mkdocs.yml) next to the FOLDER that contains the documentation.

TL;DR. Convention over configuration sucks sometimes.

### Steps

- [x] Added / updated documentation
- [x] I read the [contribution documentation](https://github.com/hedgedoc/hedgedoc/blob/master/CONTRIBUTING.md) and signed-off my commits to accept the DCO.

2021-01-04 22:05 UTC, DerMolly requested changes
We should change the file names in dev/documentation.md

2021-01-04 22:25 UTC, DerMolly requested changes

2021-01-04 22:25 UTC, DerMolly commented on docs/content/dev/documentation.md
>  1. make sure you have python3 installed
There should be a 
0. cd docs
?

2021-01-04 22:51 UTC, DerMolly approved these changes

2021-01-04 23:52 UTC, ErikMichelson requested changes

2021-01-04 23:52 UTC, ErikMichelson commented on docs/content/dev/documentation.md
>  3. start the mkdocs dev server `mkdocs serve` or let it build the documentation `mkdocs build`
As we have full sentences in this document and not only bullet-points, I'd suggest capitalizing the first letter of each point and end it with a dot.

2021-01-04 23:52 UTC, ErikMichelson commented on docs/content/dev/documentation.md
> +Messor Structor builds and deploys the documentation by finding all branches that follow the pattern `v*` and build each one seperatly via `mkdocs` by first installing the dependencies from `requirem
```suggestion
Messor Structor builds and deploys the documentation by finding all branches that follow the pattern `v*`. For each branch the docs are generated seperatly by first installing the dependencies from `requirements.txt` and then running mkdocs. Afterwards the menu go template is used to include a version switcher in the theme and make all the different versions available.
```

The long "this is done by a for each done by b" sentence structure is quite hard to read. Maybe this sounds easier to understand?

2021-01-05 10:17 UTC, mrdrogdrog commented
btw: here is a demo: https://mrdrogdrog.github.io/hedgedoc-test/

2021-01-05 10:36 UTC, ErikMichelson approved these changes

2021-01-05 15:24 UTC, davidmehren approved these changes

2021-01-05 16:16 UTC, DerMolly requested changes

2021-01-05 16:16 UTC, DerMolly commented on README.md
> +into its own organisation. [A longer writeup can be read in the history][history].
Well this links not really to a longer write-up, anymore. Maybe try to use the same text I used in `docs/content/index.md`?

2021-01-05 16:20 UTC, DerMolly approved these changes

2021-01-05 16:27 UTC, merged