NotesController: Do not crash when on nonexistent notes
hedgedoc/hedgedoc pull request #703
Opened 2021-01-09 21:41 UTC by davidmehren

### Component/Part
NotesController

### Description
This PR adds proper error handling and returns 404 when a note does not exist.
Previously, we leaked the `NotInDBError` and sent a 500 status code.

### Steps

- [x] Added implementation
- [x] Added / updated tests
- [x] I read the [contribution documentation](https://github.com/hedgedoc/hedgedoc/blob/develop/CONTRIBUTING.md) and
  signed-off my commits to accept the DCO.

### Related Issue(s)

2021-01-09 21:43 UTC, DerMolly requested changes

2021-01-09 21:43 UTC, DerMolly commented on src/api/public/notes/notes.controller.ts
> + * SPDX-FileCopyrightText: 2020 The HedgeDoc developers (see AUTHORS file)
I think this is wrong

2021-01-09 21:52 UTC, davidmehren commented on src/api/public/notes/notes.controller.ts
> + * SPDX-FileCopyrightText: 2020 The HedgeDoc developers (see AUTHORS file)
fixed

2021-01-10 09:58 UTC, InnayTool approved these changes

2021-01-10 14:14 UTC, DerMolly approved these changes

2021-01-10 16:42 UTC, merged