config: split config up
hedgedoc/hedgedoc pull request #733
Opened 2021-01-15 16:04 UTC by DerMolly

### Component/Part
config

### Description
This PR splits the config up. This is necessary to correctly work with nestks.

### Steps

- [x] Added implementation
- [x] Added / updated tests
- [x] I read the [contribution documentation](https://github.com/hedgedoc/hedgedoc/blob/develop/CONTRIBUTING.md) and
  signed-off my commits to accept the DCO.

2021-01-16 22:42 UTC, InnayTool approved these changes

2021-01-17 20:21 UTC, InnayTool approved these changes

2021-01-19 11:28 UTC, davidmehren requested changes
In addition to the bits I commented on, this PR exacerbates an existing problem:  
The error messages when the validation of the config fails are unhelpful. Previously, they didn't reference the name of the environment variable, but you had an idea how that could look like when the error complained about `database.username` not being present.

Now, the error will only say that `username` is missing, which is completely not helpful.
We need to improve the messages here ASAP.

2021-01-19 11:28 UTC, davidmehren commented on src/media/media.service.spec.ts
> +          load: [appConfigMock, mediaConfigMock],
`appConfigMock` can be removed

2021-01-19 11:28 UTC, davidmehren commented on test/public-api/media.e2e-spec.ts
> +          load: [appConfigMock, mediaConfigMock],
`appConfigMock` can be removed

2021-01-19 11:28 UTC, davidmehren commented on test/public-api/notes.e2e-spec.ts
> +          load: [appConfigMock, mediaConfigMock],
`appConfigMock` can be removed

2021-01-19 11:57 UTC, davidmehren approved these changes

2021-01-19 11:58 UTC, merged