auth: Fix handling of internal server errors
hedgedoc/hedgedoc pull request #776
Opened 2021-01-27 20:59 UTC by DerMolly

### Component/Part
auth

### Description
This PR catches all NotInDbErrors and TokenNotValidError and transform them to UnauthorizedException with the correct message.
This prevents nest from telling the api user that an internal server error has happened and instead display the correct http error code 401.

### Steps

- [x] Added implementation
- [x] I read the [contribution documentation](https://github.com/hedgedoc/hedgedoc/blob/develop/CONTRIBUTING.md) and
  signed-off my commits to accept the DCO.

### Related Issue(s)
fixes #775

2021-01-27 22:37 UTC, InnayTool submitted a review, later dismissed

2021-01-29 19:06 UTC, davidmehren requested changes

2021-01-29 19:06 UTC, davidmehren commented on src/auth/auth.service.ts
>      }
Please use something like
```
} catch (e) {
  if (e instanceof NotInDBError) {
    throw new UnauthorizedException(e.message);
  }
  throw e;
}
```
to ensure that only the expected error is caught.

2021-01-29 19:19 UTC, InnayTool submitted a review, later dismissed

2021-01-29 19:34 UTC, InnayTool approved these changes

2021-01-29 19:52 UTC, davidmehren approved these changes

2021-01-29 19:52 UTC, merged