Docs: Emphasize the difference between branches
hedgedoc/hedgedoc pull request #789
Opened 2021-01-30 17:38 UTC by davidmehren

### Component/Part
docs

### Description
To further reduce confusion between the `develop` and `master` branches,
this PR adds more information about them in the README
and the contribution docs.

### Steps

- [x] Added / updated documentation
- [x] I read the [contribution documentation](https://github.com/hedgedoc/hedgedoc/blob/develop/CONTRIBUTING.md) and
  signed-off my commits to accept the DCO.

2021-01-30 17:48 UTC, InnayTool requested changes

2021-01-30 17:48 UTC, InnayTool commented on README.md
> +⚠️⚠️⚠️ **Important:** We are currently working on HedgeDoc 2, a complete rewrite of HedgeDoc. Please note the following:
Maybe we should include a warning in the title of the README to make it make as obvious as possible.

2021-01-30 17:58 UTC, mrdrogdrog requested changes
What @InnayTool  says

2021-01-30 18:02 UTC, mrdrogdrog approved these changes

2021-01-30 18:12 UTC, InnayTool approved these changes

2021-01-30 19:05 UTC, SISheogorath commented
Honestly speaking, I think this change will not make a big difference to potentially wrong commits. People are confused by the default branch, not the README. Since GitHub is built do work towards [GitHub Flow](https://guides.github.com/introduction/flow/), which has a rolling default branch, no release or development branch system. Therefore whatever is the default branch, will receive the PRs.

So probably just making the master branch the default branch until there is an actual release of 2.0 seems to solve the problem encountered better. But that's just my opinion. 🤷🏻

2021-02-01 20:33 UTC, DerMolly approved these changes

2021-02-01 20:54 UTC, DerMolly submitted a review, later dismissed

2021-02-01 20:54 UTC, ErikMichelson submitted a review, later dismissed

2021-02-01 20:54 UTC, InnayTool submitted a review, later dismissed

2021-02-01 21:05 UTC, mrdrogdrog approved these changes

2021-02-01 21:20 UTC, InnayTool approved these changes

2021-02-01 21:20 UTC, DerMolly approved these changes

2021-02-01 21:21 UTC, merged