Config: Add forbiddenNoteIds to AppConfig
hedgedoc/hedgedoc pull request #937
Opened 2021-02-20 21:28 UTC by DerMolly

### Component/Part
config, notesService

### Description
This PR adds the forbiddenNoteIds to the AppConfig.

Also uses this config in the notes service and the appropriate tests.

### Steps

- [x] Added implementation
- [x] Added / updated tests
- [x] Added / updated documentation
- [x] I read the [contribution documentation](https://github.com/hedgedoc/hedgedoc/blob/develop/CONTRIBUTING.md) and
  made sure that:
  - My commits are signed-off to accept the DCO.
  - This PR targets the correct branch: `master` for 1.x & docs, `develop` for 2.x

### Related Issue(s)
fixes #519

2021-02-20 23:38 UTC, InnayTool approved these changes

2021-02-27 13:12 UTC, davidmehren reviewed
Looks good!

Currently, we only check for a forbidden id when creating a new note. We probably also want to do this when accessing already existing notes?

2021-02-27 14:02 UTC, DerMolly commented
> Currently, we only check for a forbidden id when creating a new note. We probably also want to do this when accessing already existing notes?

Probably not wrong…

2021-02-27 22:19 UTC, InnayTool approved these changes

2021-02-28 00:34 UTC, InnayTool approved these changes

2021-03-06 16:36 UTC, davidmehren requested changes

2021-03-06 16:36 UTC, davidmehren commented on src/notes/notes.service.ts
> +        'createNote',
```suggestion
        'getNoteByIdOrAlias',
```

2021-03-06 16:36 UTC, davidmehren commented on src/notes/notes.service.ts
> +          `A note with the alias '${alias}' is forbidden by the administrator.`,
```suggestion
          `Creating a note with the alias '${alias}' is forbidden by the administrator.`,
```

2021-03-06 16:36 UTC, davidmehren commented on src/notes/notes.service.ts
> +        `A note with the alias '${noteIdOrAlias}' is forbidden by the administrator.`,
```suggestion
        `Accessing a note with the alias '${noteIdOrAlias}' is forbidden by the administrator.`,
```

2021-03-06 16:49 UTC, DerMolly commented on src/notes/notes.service.ts
> +        'createNote',
fixed

2021-03-06 16:49 UTC, DerMolly commented on src/notes/notes.service.ts
> +          `A note with the alias '${alias}' is forbidden by the administrator.`,
fixed

2021-03-06 16:49 UTC, DerMolly commented on src/notes/notes.service.ts
> +        `A note with the alias '${noteIdOrAlias}' is forbidden by the administrator.`,
fixed

2021-03-14 15:06 UTC, davidmehren approved these changes

2021-03-14 15:06 UTC, merged